[[use_case_indoor_navigation_detail]]
=== Indoor Navigation Use Case

With the complexification of urban constructions that are increasingly leveraging vertical spaces (high rise and underground), navigating the indoor environment is becoming more and more challenging. While reliable localization system is still the biggest challenge for indoor navigation applications, the perfect map to support smart navigation is yet to be fully defined but PoI plays a critical role in its functionalities. In indoor navigation, a PoI either plays the role of a destination, or a "landmark" on the agent's way to improve the navigation experience. In this document, we select few navigation scenarios and suggest PoI examples that an application (e.g., an navigation app) would need to support them.

==== Scenario 1: 

A pedestrian may be looking for a meeting room in a building they are not familiar with. From the entrance to the meeting room, the navigation app may require the description of the:

* Levels
** Level number
** Level access (stairs, escalators, lifts)
** Entrance/exit level
* Rooms
** Number/Name
** Functions (e.g., restroom, waiting room, etc.)
* "Landmarks" (strong cues for guidance)
** printers 
** coffee machines
** artefacts, 
** Wallpapers,
** etc.
* Accessible spaces (e.g. unrestricted areas, etc.)

==== Scenario 2:

There is an emergency situation in a multi storey building, and firefighters need to get to a room to help evacuating some people. In addition to information of scenario 1, their navigation system may require the description of the:

* Openings
** Emergency exits
** Number of exits per floor
** size of exits (may have influence on the type of tools to carry for intervention)
* Rooms
** Dropped ceilings
** Storage rooms
* Extinguishers
* Hazardous installations/materials 

