[[package_drop_off_and_pick_up_detail]]
=== Package Drop off and Pick Up Services Use Case

For commercial or residential customers, package delivery and pick up logistics requires considerable attention to detail (e.g., pick up location, restrictions, time), and tracing (tracking) for efficient space use, billing and insurance purposes. Customers may end up waiting for either a delivery or a pick up that is late, or miss the connection if the delivery is early, and fuel consumption associated with individual addresses may be greater than services using a pooled location (individually-secured containers). Space in delivery vehicles can also be calculated and optimized when the package details are associated with the point of interest. Some service providers use systems to manage a "multi-customer" delivery and return location.

The customer needs to be assigned or choose a specific section (locked cubicle) that meets the package needs. Each cubicle is a point of interest within a larger "multi-customer" container, within a secured or outdoor business facility. This means that static metadata such as the street address, open hours of the facility, the latest time for drop off, cubicle's dimensions must be associated with each unit.

In addition to maintaining the static metadata for a cubicle or group of cubicles, there is dynamic data such as the weight of a package (if the cubicle is equipped with weight sensing), a unique access code for a cubicle (to be assigned each time there is a new drop off or pick up scheduled), and time of cubicle access (occupancy status). The dynamic information for each unit (PoI) can be integrated with a real-time route planning system, to release a cubicle for a future customer's use and customer back end (e.g., for billing).
