
[[ug_current_practices_section]]
== Survey of Selected Current Practices

Most usages of this POI Conceptual Model standard will need to add extra _attributes_ (named properties) in a *POI_Payload* object.
There are a number of attributes that are likely to come up often. Among the most common are:

* Multilingual names
* Addresses, including multilingual addresses
* Categories
* Business Hours
* Telephone Number

Since there are extant standards and practices for representing these, this section will survey those.
The next section will then recommend how to model these attributes in a *POI_Payload*.

=== Some Common POI Information Practices and Standards ===

Before discussing the individual attributes, here are some of the references consulted for this survey:

Indoor Mapping Data Format (IMDF)::
https://docs.ogc.org/cs/20-094/[IMDF] is an OGC Community Standard, originally developed by Apple, for indoor maps
It can be used, for example, to map airports, malls, and train stations.
It is a JSON format, based on GeoJSON.
The concept of an https://docs.ogc.org/cs/20-094/Occupant/[Occupant] is very close to that of a POI representing a business.

OpenStreetMap::
https://wiki.openstreetmap.org/wiki/Main_Page[OpenStreetMap] is a community-built map of the world.
Some of its https://wiki.openstreetmap.org/wiki/Map_features[Primary Features] could be called POIs,
and the https://wiki.openstreetmap.org/wiki/Tags[tags] of such features are similar to our attributes.
The OpenStreetMap data model is a https://github.com/openstreetmap/openstreetmap-website/blob/master/db/structure.sql[database schema].
Things are called _elements_ and _tags_ are used to provide the data for each element.

Overture Maps::
https://docs.overturemaps.org/schema/[Overture Maps] is developed by a foundation as a map built on open data.
It has a schema for https://docs.overturemaps.org/schema/reference/places/place/[places] that are essentially POIs.
Overture uses OGC's feature model, and defines its data model schema using a JSON schema.

CityGML::
https://www.ogc.org/standard/citygml/[CityGML] is an OGC standard for 3D city models.
It is mostly about the buildings and other city infrastructure, rather than the occupants of the buildings.
However, it is useful to see how it models addresses.

Google Hotels::
Google provides an XML schema for uploading listings, and a public example of this is the
https://developers.google.com/hotels/hotel-prices/dev-guide/hlf[Hotels listing] schema.
Hotels are a subset of POIs but are otherwise very similar.

Schema.org::
https://schema.org/[Schema.org] is a set of recommended schema for modeling various things on the web.
It specifies markup for various https://schema.org/Property[Properties], some of which are relevant to POIs.
A primary use is for putting _microdata_ into web pages to give information to search engines.

XML Schema::
https://www.w3.org/TR/xmlschema11-2/[XML Schema Definition Language] models a number of primitive data types,
some of which (language, dates and times) are relevant to this survey.

RFC5646::
https://tools.ietf.org/html/rfc5646[RFC 5646] _Tags for Identifying Languages_ is an Internet Best Practices
guide to tags for identifying natural languages.

Inspire::
Inspire aims to create a European Union Spatial Data Infrastructure.
The https://knowledge-base.inspire.ec.europa.eu/publications/inspire-metadata-implementing-rules-technical-guidelines-based-en-iso-19115-and-en-iso-19119_en[Inspire Metadata Implementing Rules] has some things to say about multilingual strings.

ISO 19115: Geographic information - Metadata::
https://www.iso.org/standard/53798.html[ISO 19115-2014] describes a schema for
geographic information services by means of metadata.
It has https://schemas.isotc211.org/19115/-1/lan/1.3/[schema] for language localization
that Inspire based its recommendations on.

=== Multilingual Names ===

POIs can have their names expressed differently in different natural languages:
for example "la tour Eiffel" in French is "Eiffel Tower" in English and Eiffelturm in German.

*IMDF* https://docs.ogc.org/cs/20-094/Occupant/index.html[Occupants] have a _name_
which has type https://docs.ogc.org/cs/20-094/Reference/index.html#labels[_LABELS_].
LABELS are a JSON object used to express a string label in one or more langauges.
The JSON object has member names that are languages, with the corresponding
member values being the label in that language.
For example:

```json
    name: {
      "en-US": "Center Pavillion",
      "en-GB": "Centre Pavillion"
    }
```
IMDF says that the langage member names should be a LANGUAGE_TAG, which is
defined in their https://docs.ogc.org/cs/20-094/Reference[reference section]
as an https://tools.ietf.org/html/rfc5646[RFC 5646] compliant language tag and sub-tag, script, and region subtag
registered in the
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry[IANA Language Subtag Registry].
IMDF requires that language tags may not be duplicated in a LABELS.
An IMDF archive comes with a https://docs.ogc.org/cs/20-094/Manifest[Manifest] containing metadata about the described venue.
Among the metadata is a _language_, whose value is the _default language_ tag for the venue.
There is a requirement that all LABELS must contain an entry for the default language.

In *OpenStreeMap*, elements are given names with a _name=_ tag, which is decribed https://wiki.openstreetmap.org/wiki/Names#Localization[here].
Additionally, there is a long article on https://wiki.openstreetmap.org/wiki/Multilingual_names[Multilingual names].
There can be multiple _name=_ tags for an element, each giving the name in another language.
The bare _name=_ tag gives the default language name, used locally.
Names in other languages use the form _name:code=_, where _code_ is
a language's https://www.loc.gov/standards/iso639-2/php/code_list.php[ISO 639-1 alpha-2 code (in the second column)],
or https://www.loc.gov/standards/iso639-2/php/code_list.php[ISO 639-2/T (alpha-3)] code.
It is recommended that the local name be repeated with an explicit language code,
so that an implementation doesn't have to guess the local language.
For example:

```
    name=la tour Eiffel
    name:fr=la tour Eiffel
    name:en=Eiffel Tower
    name:de=Eiffelturm
```

In *Overture Maps*, names are objects with a _primary_ member (a string), and a _common_ member
which is an object that itself contains members whose names are
https://en.wikipedia.org/wiki/IETF_language_tag[IETF-BCP47] language tags
and whose values are strings.
For examplehttps://github.com/OvertureMaps/schema/blob/main/task-force-docs/places/overture_categories.csv

```json
    "names": {
      "primary" : "Statue of Liberty",
      "common" : {
         "fr" : "Statue de la Liberté",
         "it" : "Statua della Libertà"
      }
    }
```

The primary name is expected to be the name in the localized langauge, and the common names
give the name in other languages.
The IETF-BCP47 language codes are expected to be in the
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry[IANA language subtag registry].

Overture Maps allows an additional object in the _names_ element: a _rules_ object.
It allows for expressing such variants as "short", "alternate", or "official", and includes
an explicit _language_ member and _value_ member.

*Google Hotels* specifies the language at the file level only:
that is, the entire collection of POIs is expected to have names in a single language,
and that language is given by a _language_ XML element in the https://www.gstatic.com/localfeed/local_feed.xsd[schema].
The language is expected to be an http://www.w3.org/WAI/ER/IG/ert/iso639.htm#2letter[ISO 639 lowercase 2-letter language code].

*CityGML* and *Schema.org* appear not to have addressed the issue of multilingual names.

*Inspire* has an Annex A.6 in their https://knowledge-base.inspire.ec.europa.eu/publications/inspire-metadata-implementing-rules-technical-guidelines-based-en-iso-19115-and-en-iso-19119_en[Inspire Metadata Implementing Rules]
which gives their method for representing any multilingual metadata that has type CharacterString and a "free text domain".
For such metadata, a subtype of CharacterString called PT_FreeText aggregates any number of textGroup objects.
A textGroup in turn has one or more LocalisedCharacterString, which in turn has a locale member of type PT_Locale.
Finally, a PT_Locale has three members: a language, a country, and a characterEncoding.
For example

```
     <PT_FreeText>
       <textGroup>
         <LocalisedCharacterString locale="#locale-fr">Résumé succinct
            du contenu de la ressource</LocalisedCharacterString>
       </textGroup>
     </PT_FreeText>
```

where the local-fr referred to in the example is specified elsewhere in the file, as, e.g.,

```
    <locale>
       <PT_Locale id="locale-fr">
         <languageCode>
           <LanguageCode
             codeList="http://www.loc.gov/standards/iso639-2/"
             codeListValue="fre"> French </LanguageCode>
         </languageCode>
         <characterEncoding>
           <MD_CharacterSetCode
             codeList="resources/codelist/gmxcodelists.xml#MD_CharacterSetCode"
             codeListValue="utf8">UTF 8</MD_CharacterSetCode>
         </characterEncoding>
       </PT_Locale>
     </locale>
```
Note that the language codes are taken from ISO639, but that is specifically given as an attribute.
Inspire has mechanisms for specifying a default language for a whole file.
Since it is expressed as an XML schema, they recommend that things need to contain
character strings either be straight character strings, or they get "retyped"
(by using an XML xsi:type="gmd:PT_FreeText_PropertyType" attribute).

==== Addresses, including Multilingual Addresses ====

There are many ways of expressing addresses of POIs.
And, like POI names, addresses have country, locality, and street names that are different in different languages:
e.g., Spain in English is España in Spanish.

In *IMDF*, an https://docs.ogc.org/cs/20-094/Address/index.html[Address] is a Feature object
containing a number or properties:

* _address_: formatted postal address, excluding suite/unit identifier, i.e. "123 E. Main Street".
* _unit_: if present, a qualifying official or proprietary unit/suite designation, i.e. "2A"
* _locality_: the official locality (e.g. city, town) component of the postal address
* _province_: if present, Province (e.g. state, territory) component of the postal address, using
https://www.iso.org/standard/72483.html[ISO 3166-2]
* _country_ : country component of the postal address, using
https://www.iso.org/iso-3166-country-codes.html[ISO 3166]
* _postal_code_ : mail sorting code associated with the postal address
* _postal_code_ext_ : mail sorting code extension associated with the postal code
* _postal_code_vanity_ : mail sorting code extension associated with the postal code

There is nothing said about expressing the _address_ or
CityGML appears not to have addressed the issue of internationalized names.
 _locality_ in different languages,
so presumably the local language is expected for those.
By using ISO standards for _province_ and _country_, those can be tranlated into other languages
when converting the codes to full names.

In *OpenStreetMap*, addresses are assigned to elements by giving them values for various _addr:xxx=_ tags,
as described in https://wiki.openstreetmap.org/wiki/Addresses[this article].
The tags are similar to those used by IMDF, but more comprehensive and more structured.
Consult https://wiki.openstreetmap.org/wiki/Map_features#Addresses[here] for the full list.
There is an attempt to fully structure addresses, rather than leaving the street etc. as an unstructured string,
though there is a fallback _addr:full=_ tag for when structuring just doesn't work.
For example:

```
    addr:housenumber=1000
    addr:street=5th Avenue
    addr:city=New York
    addr:state=NY
    addr:country=US
```

For values that can be multilingual, the tags can have a language code added to them after a colon,
just as they were in the _name:code=_ tags of the previous part of this section.
For example:

```
    addr:city:en=Munich
    addr:city_de=München
```

In *Overture Maps*, the https://docs.overturemaps.org/schema/reference/addresses/address/[address schema]
has country, postcode, street, number, and unit, and then a number of "address levels" to capture
all the various levels of administrative areas that might be present, in an ordered by unlabeled way.
An example is:

```json
  "properties": {
    "theme": "addresses",
    "type": "address",
    "version": 0,
    "country": "US",
    "address_levels": [
      {
        "value": "MA"
      },
      {
        "value": "NEWTON CENTRE"
      }
    ],
    "postcode": "02459",
    "street": "COMMONWEALTH AVE",
    "number": "1000"
  }
```

The note that they loosely followed the ideas of https://openaddresses.io/[OpenAddresses].
It appear that they do not explicitly address the issue of multilingual address components.

=== Categories ===

The "Category" of a POI is a word that describes the main purpose, use, or description of the POI. It is a word that would fill in the blank in the statement: "This POI is a +_______+". Example categories might be *School* or *Clothing Store*. Usually one would like the most specific category that applies (e.g.,. preferring *Men's Clothing Store* over *Clothing Store*, but the latter over *Store*).

There are tens of thousands of possible categories, and there is no generally accepted category list that this recommendation can confidently point to. Some examples of some standard category lists are:

[#category-lists-table,reftext='{table-caption} {counter:table-num}']
.Category Lists
[cols="1,4",width="90%"]
|===
|NAICS: |
   The North American Industry Classification System. This is used by the US Census to classify businesses according to their economic activity. They are numeric codes with English language descriptors. While they are meant to classify activities that are not necessarily connected to particular POIs, this classification system is still applicable to POIs, though maybe not at the deepest level of specificity desired. https://www.census.gov/naics/[ref]

|OpenStreetMap: |
   Open Street Map uses a "Free tagging system" to associate multiple key/value pairs with features (which could be POIs). While not comprehensive and endlessly extensible, it is usually possible to find a +key=attribute+ string that could be used as a category: e.g., +building=stadium+. +craft=winery+, or +shop=butcher+. https://wiki.openstreetmap.org/wiki/Map_features[ref]

|OGC Indoor Mapping Occupant Category: |
   The OGC Indoor Mapping OGC Community standard (https://docs.ogc.org/cs/20-094/index.html[ref]) has an https://docs.ogc.org/cs/20-094/Categories/index.html#occupant[*Occupant category*] list that has a number of useful categories for POIs.

|Overture Maps: |
    Overture Maps has a "categories" tag of a place, which has a required "primary" category (a string), and an optional list of "alternate" categories.
    The list of available categories is https://github.com/OvertureMaps/schema/blob/main/docs/schema/concepts/by-theme/places/overture_categories.csv[here].

|GeoNames Ontology: |
   The GeoNames geographic database (https://www.geonames.org/[ref]) has an http://www.geonames.org/ontology/documentation.html[OWL ontology] for Features (which are akin to POIs). It has many kinds of POIs but not many types of commercial shops and restaurants.
|===

=== Business Hours ===

The "business hours" or "opening hours" of a POI are the times when the POI is "open for business", or, more generally just the times at which the general public can visit a POI. There may be more than one open interval on a day (e.g., mealtimes for a restaurant). Often, opening hours can be different for each day of the week, but are the same week after week. But occasionally POIs have more complicated opening hours (e.g., "closed the first Monday of every month from May to October"). Also, POIs often have special hours for vacations and holidays.

There are several standards to choose from to express business hours. A simple standard, which covers the usual case of weekly hours that repeat, is the Schema.org *openingHours* property (https://schema.org/openingHours[ref]). This standard also assumes that the timezone of the opening hours is clear (presumably, the timezone of the POI in question). An example of opening hours expressed in this format is:

.Simple Opening Hours Example
[source,text]
----
   openingHours: Tu-Fr 9:00-17:00
   openingHours: Sa,Su 9:00-19:00
----

A more general standard, which handles non-weekly repeating as well as exceptions for vacations, holidays, etc., is the _iCalendar_ specification (https://www.rfc-editor.org/rfc/rfc5545[RFC 5545]), in particular its _Calendar Availability_ component (https://www.rfc-editor.org/rfc/rfc7953[RFC 7953]). While one could specify an entire calendar using these standards, the needs of specifying opening hours are served well enough by just giving the Availability part. For example, to specify opening hours in France that one might informally specify as "M: 11am-7:30pm, T-Sat: 10am-7:30pm, Sun: closed; closed Aug 1 - Aug 31", the value according this this standard would be:

.Opening Hours Example
[source,text]
----
   openingHours:
      BEGIN:VAVAILABILITY
      UID:uid11
      DTSTAMP:20220101T000000Z
      PRIORITY:0
      BEGIN:AVAILABLE
      UID:uid12
      DTSTART;TZID=Europe/Paris:20220103T110000
      DTEND;TZID=Europe/Paris:20220103T193000
      RRULE;FREQ=WEEKLY;BYDAY=MO
      END:AVAILABLE
      BEGIN:AVAILABLE
      UID:uid13
      DTSTART;TZID=Europe/Paris:20220104T100000
      DTEND;TZID=Europe/Paris:20220104T193000
      RRULE;FREQ=WEEKLY;BYDAY=TU,WE,TH,FR,SA
      END:AVAILABLE
      END:VAVALABILITY
      BEGIN:VAVAILABILITY
      UID:uid14
      DTSTAMP:20220101T000000Z
      PRIORITY:5
      BEGIN:AVAILABLE
      UID:uid15
      DTSTART;TZID=Europe/Paris:20220801T000000
      DTEND;TZID=Europe/Paris:20220831T235959
      RRULE;FREQ=YEARLY;BYMONTH=8
      END:AVAILABLE
      END:VAVALABILITY
----

*OpenStreetMap* has an Hours type that is specified https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification[here].
It is a grammar that has been developed by the community over the years and is quite flexible for representing exceptions, holidays, etc.
One writes a set of rules, where later rules can override former ones (thereby providing exceptions).
There is provision for things like holidays, particular weeks or days of the month, "event" times (e.g., "sunrise").
It is much more readable than the iCalendar specification, but doesn't have provision for timezones.
Timezones are not really necessary for the POI application, beacuse the timezone is implied by the POI's position on earth.

.OpenStreetMap Hours Example
[source,text]
----
   Mo,Tu,Th,Fr 12:00-18:00; Sa,PH 12:00-17:00; Th[3],Th[-1] off
----

This example says that the POI is open on Monday, Tuesday, Thursday, and Friday, from noon to 6pm.
On Saturdays and public holidays, it is open from noon to 5pm.
It is closed on the third Thursday and the last Thursday of the month.

*IMDF* has an Hours type that follows the OpenStreetMap format.

Neither *Overture Maps* nor *Google Hotels* specify an opening hours property.


=== Telephone Number ===

The _ITU-T E.164 standard_ (https://www.itu.int/rec/T-REC-E.164[ref]) specifies a format for telephone numbers. It starts with a recommended *+* sign, followed by up to fifteen digits (with no spaces or other punctuation). The digits will typically be a country code, then an area code, then a local number. For example, the US local number 555-1234 with an area code of 212 would be represented by this character string:

.ITU-T E.164 Telephone Number
[source,text]
----
   +12125551234
----

Another ITU standard is _ITU_T E.123_ (https://www.itu.int/rec/T-REC-E.123[ref]).
It specifies ways of writing phone numbers that are different depending on whether they are in the country or international.

And RFC3966 (https://www.rfc-editor.org/rfc/rfc3966.html[ref]) gives the syntax for phone numbers used in a _tel_ URI.

*IMDF* has a Phone type that specifies using E.164.

*Overture Maps* has a phone type that is a list of strings; the format of the strings is left unspecified.

*OpenStreeMap* has a phone type that is specified https://wiki.openstreetmap.org/wiki/Key:phone[here].
It gives several alternatives for the phone string:

* phone=number where the number should be in international (ITU-T E.164) format
* phone=+<country code> <area code> <local number>, following the ITU-T E.123 and the DIN 5008 pattern
* phone=+<country code>-<area code>-<local number>, following the RFC 3966/NANP pattern)
* phone=+<country code> <area code> <local number>\;ext=<extension> is allowed by RFC3966 to specify a local extension

It also allows a fax= tag to give a separate fax number.

*Google Hotels* has a phone container with a "type" attribute that can be one of: fax, main, mobile, tdd, tollfree.
The format of the phone number itself is not specified.

