
[[ug_nonstandard_attributes_section]]
== Payload: Nonstandard Attributes

An _attribute_ is a named property of a feature. While this POI Conceptual Model Standard specifies some standard attributes (e.g., lifetime attributes), most applications will need to define and use some attributes that are not normatively defined by the standard. The mechanism for including non-standard attributes in a POI is to use the *hasPayload* property, whose type is zero or more *POI_Payload* values.

=== Using POI_Payload

A *POI_Payload* is only partially specified in this POI Conceptual Model Standard. These properties are specified:

usesSchema:: The value identifies a _schema_ for the payload. How this identification is done and what the schema looks like depends on the implementation technology used. We'll see some examples below. The schema describes the _syntax_ for the other properties of the payload, and the value for identifying the schema is typically a _URI_. There can be more than one schema, but the intent is that these will represent the same conceptual model of a payload, perhaps for different implementation technologies.

hasDefinition:: The value is a companion to the schema referenced by *usesSchema*, and it describes the _semantics_ of the various payload fields. Typically, this will be plain text descriptions of the properties, what standards they adhere to, etc.

hasFeatureOfInterest:: This indicates the Feature of Interest that the payload is for. There can be zero or more of these.

For example, suppose an application needed an attribute called *isPublic*, whose value is true or false depending on whether or not the POI is something the general public can visit. A particular POI could include a *hasPayload* association to a *POI_Payload* that looks like this in conceptual form:


[cols="1,2,3"]
|===
|*Attribute*|*Value type and multiplicity*|*Definition*

|usesSchema
|PayloadSchema [1..*]
|Refers to the schema(s) for this payload
|hasDefinition
|PayloadDefinition [0..1]
|Refers to the definition of the payload attributes
|isPublic
|Boolean [1..1]
|Is this POI a publicly visitable place
|===

Both *PayloadSchema* and *PayloadDefinition* should be a *Link*.

Suppose the implementation technology is JSON. Here is how the above payload might be used in a POI expressed in JSON:

.POI Example of a POI with a POI_Payload (JSON)
[source,JSON]
----
   {
      "type": "Feature",
      "geometry": {"type": "Point", "coordinates": {45.14, -94.69}},
      "featureID": 693842,
      "name": {"name" : "Midtown Library"},
      "contactInfo" : {"role": "city representative"},
      "hasPayload": [
         "usesSchema" : [
            {
               "href" : "https://example.org/schema/egpoi.json",
               "rel" : "describedby"
            }
         ],
         "hasDefinition" : {
               "href" : "https://example.org/schemadef/egpoi",
               "rel" : "type"
         },
         "isPublic:" : true
      ]
   }
----

The value of the *usesSchema* property should reference a schema that might look like this:

.POIProperty Example Payload Schema (JSON)
[source,JSON]
----
  {
    "$schema": "http://json-schema.org/draft/2020-12/schema#",
    "$id": "https://example.org/schema/egpoi.json",
    "title": "POI Payload for POI with IsPublic property",
    "typee": "object",
    "properties": {
      "isPublic": { "type": "boolean"}
    }
  }
----

The value of the *hasDefinition" property should reference a file that describes the semantics corresponding to the above schema. It might look something like this:

.POIProperty Example Payload Definition
[source]
----
  isPublic: This field is a boolean that should be true if the POI is publicly visitable, else false.
----

=== Recommended Schema and Semantics for Common Nonstandard Attributes

There are a number of attributes that commonly are needed in use cases for POIs yet are not standardized in the POI-CM. This section suggests a recommended schema for these common nonstandard attributes.
The attributes discussed are the same ones surveyed in the previous *Current Practices* section.

==== Multilingual Names ====

In the current practices, there were three broad groups:

[cols="1,2"]
|===
|Implied Language
|No language specified with each name string. Perhaps there is a file-scoped language, known by some external means or by one file-scoped metadata element.
|Separate Per-Language Attributes
|Multiple attribute names that have the language as a suffix (e.g., "name", "name:fr", "name:en", ...) with the unsuffixed version representing a default langauge.
|Complex Attributes
|Names are sequences or objects, not character strings. Each element of the sequence is an object has a character string (the name itself) along with an attribute that says what language it is in. If the name is an object, then it has a default-language string and optional other-language strings in a sequence as described previously.
|===

There are several variants of the Complex Attribute method:

===== Complex Attributes: Sequence-only =====

Every name must be a sequence of objects. It might look something like this:

```json
    "name": [
      {"name" : "Statue of Liberty", "language" : "en"},
      {"name" : "Statue de la Liberté", "language" : "fr"}
    ]
```

===== Complex Attributes: Default and Sequence =====

Here the name is an object that contains a default name and a sequence.
The language of the default name could be specified by a "language" property
in the outermost object of the file.
It would look something like this:

```json
    "name" : {
      "default" : "Statue of Liberty",
      "names": [
        {"name" : "Statue of Liberty", "language" : "en"},
        {"name" : "Statue de la Liberté", "language" : "fr"}
      ]
    }
```

===== Complex Attributes: Inspire =====

To follow existing standards, the Inspire method could be used.
It is very similar to the Sequence-only method but the elements of the sequence,
instead of referring to _languages_, refer to _locales_.
This requires definitions of a number of *locales* somewhere at the file scope.
Adapted to JSON, it might look something like this:

```json
    "locales" : [
      {
         "id" : "locale_en",
         "language_code" : {
            "code_list" : "http://www.loc.gov/standards/iso639-2/",
            "code_list_value" : "en",
            "name" : "English"
         },
         "character_encoding" : {
            "code_list" : "resources/codelist/gmxcodelists.xml#MD_CharacterSetCode",
            "code_list_value" : "utf8">UTF 8</MD_CharacterSetCode>,
            "name" : "UTF8"          
         }
      },
      {
         "id" : "locale_fr",
         "language_code" : {
            "code_list" : "http://www.loc.gov/standards/iso639-2/",
            "code_list_value" : "fr",
            "name" : "French"
         },
         "character_encoding" : {
            "code_list" : "resources/codelist/gmxcodelists.xml#MD_CharacterSetCode",
            "code_list_value" : "utf8">UTF 8</MD_CharacterSetCode>,
            "name" : "UTF8"          
         }
      }
    ]
```

Then an actual name attribute would look something like:

```json
    "name": [
      {"name" : "Statue of Liberty", "locale" : "locale_en"},
      {"name" : "Statue de la Liberté", "language" : "locale_fr"}
    ]
```

===== Complex Attributes: Choice of Simple or Complex =====

In this variant, the "name" value can be one of two types: a simple string
or one of the other Complex Attribute variants.
If the value is only a simple string, then it is assumed to be in the default
language, specified at file scope.
Otherwise, the structured value will give all of the desired language variants.
The advantage of this variant is that the simple case of all-one-language yields
a file that is simple to understand and process.

===== Discussion and Recommendation =====

Here is a table of some pros and cons of the various methods discussed.

[cols="1,2,3"]
|===
|*Method*|*Pros*|*Cons*

|Implied Language
|Simple. Easy to write and use.
|The only way to handle multiple languages is to provide a choice of multiple files.
Keeping such files in sync is error-prone.
|Separate Per-Language Attributes
|Familiar to OpenStreetMap users.
Handles the one-language case well.
Compact.
|Conceptually unclean to have a number of name attributes at the same level
as other attributes.
Needs more post-processing to gather together all the names
in the internal data format.
|Complex Attributes: Sequence Only
|Moderately simple to read and process.
|Bulkier for one-language case.
Not clear what the default name to use is.
|Complex Attributes: Default and Sequence
|Handles one-language case moderately well.
Can tell what name to use by default.
|Bulkier than most other options, and still not ideal for one-language case.
|Complex Attributes: Inspire
|Closest to "standards compliant".
Allows specification of character encoding too, and in a less-verbose way
than if done per name.
|Complex to read and write (the locales part).
Need to process metadata in another part of the file and connect to each POI: a POI feature would not be standalone.
Extra complexity of indirection is only useful if multiple character encodings are needed.
|Complex Attributes: Choice of Simple or Complex
|Handles one-language case well.
Any other pros of the variant of Complex that is coupled with this.
|Need to make value-type-dependent choice when processing.
|===

The recommendation is to use the Choice of Simple or Complex attributes,
and in the case of a Complex attribute, use the Sequence Only submethod.

==== Address ====

TBD

// _TODO: check out ISO 19160:1 A conceptual model for addressing_

==== Telephone Number

The telephone number is the number to use to contact the POI to ask questions, get service, etc. The recommendation here is to use the *CI_Telephone* class from other OGC standards [TODO: cite]:

.CI_Telephone Schema
[source,JSON]
----
    "CI_Telephone": {
        "number": "CharacterString" [1..1],
        "numberType": "CI_TelephoneTypeCode" [0..1]
        }
----

where the *number* contains the dial numerals needed to reach that place. The _ITU-T E.164 standard_ (https://www.itu.int/rec/T-REC-E.164[ref]) specifies a suitable format for telephone numbers. It starts with a recommended *+* sign, followed by up to fifteen digits (with no spaces or other punctuation). The digits will typically be a country code, then an area code, then a local number. For example, the US local number 555-1234 with an area code of 212 would be represented by this character string:

.ITU-T E.164 Telephone Number
[source,text]
----
   +12125551234
----

The optional *numberType* is a one of *facsimile*, *sms*, *voice*, where *voice* is the default if the *numberType* is left out.

==== Opening Hours

The recommendation is to use the
https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification[OpenStreetMap]
grammar to describe opening hours.

==== Category

The previous section described the state of current practices for business categories.
None of them is comprehensive enough or granular enough to serve the use case of "I'm looking for a POI that offers this product, service or experience" for the full range of things people need to find. In the absence of anything better, the NAICS list seems best and the recommendation would be to use that as the code list. However, in order to allow for ultimate flexibility, the following schema is recommended.:

.Recommended Category Schema
[source,json]
----
    "category": {
        "category": "CharacterString" [0..1],
        "categorySystem": "CategorySystemCode" [0..1]
        }
----

where *CategorySystemCode* is a *CodeList* with literals *naics*, *osm*, *ogcindoor*, *geonames*, and *custom*, where *custom* is the default if none is listed, and means that the category system is basically freeform (recommended as English language text).


