[[choose_restaurant_use_case_section]]
== Choose Restaurant Use Case

=== Use Case Overview

The *Choose Restaurant* use case is where a system is desired to help users find restaurants near them and information abou those restaurants to decide which, if any, they want to use.

In order to choose a restaurant to eat in or get delivery from, users need to be able to POIs that are restaurants, with certain constraints (e.g., within a certain distance from a point on earth where the user is or expects to be). From that set of possibilities, they may wish to examine further information about each restaurant, to narrow down the choice. This information may include some or all of the following:

* Serves cuisines that the user can eat and likes.
* Is open during the hours the user intends to visit,
and/or serve the type of meal (breakfast, lunch, dinner, etc.) the user wants.
* Has service style the user prefers (take-out vs dine-in).
* Has a price level the user prefers.
* Has a bar and/or serves alcohol.
* Has delivery.
* Has order-ahead with pickup.
* Requires reservations or reservations recommended.
* Will have a busyness level that the user prefers at the time of intended vist.
* Has good reviews.
* Accepts particular payment methods.
* Has an ambience the user prefers (family-friendly, upscale, romantic, etc.).
* Has an all-you-can eat buffet.
* Shows sports on TV.
* Has a happy hour.
* Is Handicap-accessible.
* Has available free parking.
* Has health-related requirements (vaccination and/or masks).

To support this use case, a system will need a comprehensive set of restaurant POIs, each with attributes to help answer some or all of the information needs listed above.

The POI-CM standard specifies a way to represent a POI with its name, and its (latitude, longitude) position on earth. The rest of the information needed will have to be specified using non-standard attributes, as described in the xref:06-nonstandard-attributes.adoc#ug_nonstandard_attributes_section[Nonstandard Attributes] section.

=== Nonstandard Attributes for Restaurant POIs

The most important nonstandard attributes needed for the restaurant use case are:

* xref:06-nonstandard-attributes.adoc#_address[Address]
* xref:06-nonstandard-attributes.adoc#_telephone_number[Telephone Number]
* xref:06-nonstandard-attributes.adoc#_opening_hours[Opening Hours]
* xref:06-nonstandard-attributes.adoc#_category[Category]
* Website

The recommended way to represent the first four of these was discussed in the xref:06-nonstandard-attributes.adoc#ug_nonstandard_attributes_section[Nonstandard Attributes] section.
Website is intended to be the "authoritative" web page for the restaurant in question -- that is, the page that the restaurant would like users to visit if they want to learn more about their restaurant. That web page might answer many of the other attribute questions (e.g., "has a bar") in the list of the previous section.
While one could use the *CI_Contact* type from the informative annex, a simpler recommendation is to extend the schema like by addint this:

[source.JSON]
----
   "Website" {
      "url" : "CharacterString[1..1]"
   }
----

where the *url* value is a Uniform Resource Locator.

_TODO: should we repeat the whole extended POI schema here?_

=== Example ===

Putting it all together, here is an example of a restaurant POI using JSON.

[source.JSON]
----
{
    "type": "Feature",
    "geometry" : {
        "type" : "Point",
        "coordinates" : [
            45.1491802,
            -84.6907891
        ]
    },
    "properties" : {
        "featureID" : 693842,
        "name" : {
            "name" : "Chez Jacques"
        },
        "website" : {
            "url" : "http://chezjacquesrestaurant.com"
        },
        "telephoneNumber" : {
            "number" : "+13205555555"
        },
        "address" : {
            "deliveryPoint" : "400 Atlantic Ave",
            "city" : "Grove City",
            "administrativeArea" : "Minnesota",
            "postalCode" : "56243"
        },
        "category" : {
            "category" : "French Restaurant",
            "categorySystem" : "custom"
        },
        "openingHours" : {
            "openingHoursLines" : [
                "line" : "Mo-Fr 12:00-20:00",
                "line" : "Sa 12:00-22:00"
            ],
            "openingHoursFormat" : "schemadotorg"
        }
    }
}
----


An alternative method for representing the needed information is to lean more heavily on the *CI_Contact* type from the informative annex. Here is the specification of its fields:

[cols="1,2,3"]
|===
|*Attribute*|*Value type and multiplicity*|*Definition*

|address
|CI_Address [0..*]
|physical and email address at which the organisation or individual may be contacted

|contactInstructions
|CharacterString [0..1]
|supplemental instructions on how or when to"Mo-Fr 12:00-20:00 contact the individual or organisation

|hoursOfService
|CharacterString [0..*][source.JSON]
|time period (including time zone) when individuals can contact the organisation or individual

|onlineResource
|CI_OnlineResource [0..*]
|on-line information that can be used to contact the individual or organisation

|phone
|CI_Telephone [0..*]
|telephone numbers at which the organisation or individual may be contacted
|===

We have already seen the *CI_Telephone* fields in the xref:06-nonstandard-attributes.adoc#ug_nonstandard_attributes_section[Nonstandard Attributes] section.
Here are the specs for the other types mentioned:

*CI_Address*
[cols="1,2,3"]
|===
|*Attribute*|*Value type and multiplicity*|*Definition*

|administrativeArea
|CharacterString [0..1]
|state, province of the location

|city
|CharacterString [0..1]
|city of the location

|country
|CharacterString [0..1]
|country of the physical address

|deliveryPoint
|CharacterString [0..*]
|on-line information that can be used to contact the individual or organisation

|electronicMailAddress
|CharacterString [0..*]
|address of the electronic mailbox of the responsible organisation or individual

|postalCode
|CharacterString [0..1]
|ZIP or other postal code
|===

*CI_OnlineResource*
[cols="1,2,3"]
|===
|*Attribute*|*Value type and multiplicity*|*Definition*

|applicationProfile
|CharacterString [0..1]
|name of an application profile that can be used with the online resource

|description
|CharacterString [0..1]
|detailed text description of what the online resource is/does

|function
|CI_OnlineFunctionCode [0..1]
|code for function performed by the online resource

|linkage
|CharacterString [1..1]
|location (address) for on-line access using a Uniform Resource Locator/Uniform Resource Identifier address or similar addressing scheme 

|name
|CharacterString [0..1]
|name of the online resource

|protocol
|CharacterString [0..1]
|connection protocol to be used e.g. http, ftp, file,http get KVP, http POST, etc...

|protocolRequest
|CharacterString [0..1]
|protocol used by the accessed resource(to be used mainly for POST requests).
|===

where *CI_OnlineFunctionCode* is one of *browseGraphic*, *browsing*, *completeMetadata*, *download*, *emailService*, *fileAccess*, *information*, or *offlineAccess*.

With all of this in place, the need to associate an address, telephone number, and website can be addressed inside *CI_Contact*, leading to an example as follows:

[source.JSON]
----
{
    "type": "Feature",
    "geometry" : {
        "type" : "Point",
        "coordinates" : [
            45.1491802,
            -84.6907891
        ]
    },
    "properties" : {
        "featureID" : 693842,
        "name" : {
            "name" : "Chez Jacques"
        },
        "contactInfo" : {
            "address" : {
                "deliveryPoint" : "400 Atlantic Ave",
                "city" : "Grove City",
             "administrativeArea" : "Minnesota",
             "postalCode" : "56243"
            },
            "phone" : {
                "number" : "+13205555555"
            },
            "hoursOfService" {
                "Mo-Fr 12:00-20:00",
                "Sa 12:00-22:00"
            },
            "onlineResource" : {
                "linkage" : "http://chezjacquesrestaurant.com"
            }
        },
        "category" : {
            "category" : "French Restaurant",
            "categorySystem" : "custom"
        },
    }
}
----