[[poi_publication_use_case_section]]

== POI Publication Use Case

## Introduction

The Digitaal Vlaanderen (DV) POI Service is a comprehensive initiative designed to standardize and publish location-based information collected by various Flemish government organizations. Different government bodies gather valuable data across diverse domains such as education, sports, tourism, and public health, which are of significant interest to both public and private organizations. These datasets often vary in format, content, and quality, posing challenges for integration and usability. The Digitaal Vlaanderen POI Service addresses these challenges by collecting these disparate datasets, standardizing them into a common POI data model, and ensuring consistency and interoperability.

## Key Statistics of the Digitaal Vlaanderen POI Service (2024)

- Over 10 years of active service.
- 21 datasets from 8 government organizations.
- Data input in 5 different formats (shp, csv, wfs, xml, json).
- Organized into 8 themes, 17 categories, and 154 POI types.
- As of 2024, over 199,000 POIs collected for the Flanders region.

By transforming heterogeneous data into a unified POI data model, Digitaal Vlaanderen not only enhances the accessibility and usability of the information but also facilitates seamless data sharing and integration across different platforms and applications. This standardized approach enables organizations to leverage high-quality, reliable data for various purposes, including urban planning, service delivery, and innovative technological applications such as augmented reality and geospatial analytics, thereby contributing to smarter, more efficient, and more connected communities.

## Standardized POI Data Model for Central Storage

A standardized relational POI data model, such as the one developed by Digitaal Vlaanderen, is essential for ensuring consistency and reliability in representing POI data collected from various government organizations. This model translates diverse datasets into a uniform format, effectively representing locations on maps with basic information such as the name, address, coordinates, and a link to more details. By adhering to this standardized model, Digitaal Vlaanderen can integrate and manage data from multiple sources, maintaining high data quality and facilitating seamless data sharing and usage across different platforms and applications.

## POI Service Product Development

### Analysis
- Assess the information in the different datasets for content and use, focusing on relevance to users.
- Ensure accurate completion of the POI model and proper documentation.

### Modeling
- Collaborate with data managers to define the POI data model mapping.
- Determine georeferencing based on address or coordinates.
- Link addresses to central databases to obtain coordinates if necessary.
- Transform the supplied information into the POI product model, performing necessary checks and describing the data through metadata.

### Public Access
- Select the appropriate channel for the product.
- Establish arrangements for access, use, and reuse.

### Updating
- Implement a 'production line' approach during product development to process all subsequent versions efficiently.
- Manage maintenance, communication, and support.

## Translating the Digitaal Vlaanderen POI Data Model into a POI JSON Template Following the OGC Conceptual Model

Translating the Digitaal Vlaanderen POI data model into a POI JSON template involves aligning the data structure with the OGC (Open Geospatial Consortium) Conceptual Model as outlined in the OGC POI Standard. This process ensures that the data is interoperable, consistent, and adheres to international standards. The OGC Conceptual Model provides a comprehensive framework that defines the attributes, relationships, and semantics necessary for accurately representing POIs. By following this model, the POI JSON template incorporates standardized elements such as geometric data, feature identification, contact information, metadata, rights, and payload attributes.

The template should be designed to serve as both an input and output format. As an input format, it ensures that data collected from various sources adheres to a common structure, facilitating seamless integration and processing. As an output format, it ensures that the published data is consistent and usable across different applications and platforms. This dual functionality not only facilitates seamless data integration and exchange between different systems and applications but also enhances the quality and reliability of the data. The result is a robust, flexible, and scalable template that supports various use cases, including smart city applications, augmented reality, and geospatial analytics, thereby maximizing the utility and impact of the published POI data.

## Benefits for Data Publishers and Developers

- **Consistency and Interoperability**: Ensures consistency across datasets, facilitating easier integration and use of diverse data sources.
- **Efficiency and Reduced Costs**: Streamlines processes by adhering to common standards, reducing the need for custom solutions.
- **Enhanced Data Quality**: Enforces uniform formats and definitions, leading to more accurate and reliable data.
- **Simplified Data Sharing**: Facilitates collaboration and information exchange between organizations.
- **Broader Reach and Impact**: Easier dissemination and access to data, increasing its utility and impact.
- **Support for Advanced Technologies**: Enables the development of smart city applications, AR, and IoT technologies.

## Example JSON Schema Used by Digitaal Vlaanderen

```json
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [51.19391876816891, 5.1644166129636519]
  },
  "featureID": "c3bf1a5e-df00-4c93-89de-6b0e44e97806",
  "name": {
    "name": "AGC Glass Europe Mol"
  },
  "contactInfo": [{
    "role": "owner",
    "party": {
      "contactInfo": {
        "OnlineResource": "https://omgeving.vlaanderen.be/gpbv-installaties"
      },
      "name": "Afdeling Gebiedsontwikkeling, Omgevingsplanning en -projecten (GOP)"
    }
  }],
  "hasMetadata": {
    "href": "https://www.vlaanderen.be/datavindplaats/catalogus/gpbv-installaties-in-vlaanderen-in-het-kader-van-de-richtlijn-industriele-emissies-rie-via-poi-service",
    "rel": "about"
  },
  "rights": [{
    "otherConstraints": "Modellicentie_Gratis_Hergebruik"
  }],
  "hasPayload": {
    "usesSchema": [{
      "href": "https://genpoijson.org/schema/publicationpoi.json",
      "rel": "describedby"
    }],
    "onlineResources": [{
      "description": "Meer info over de installatie, waaronder de vergunningsbesluiten",
      "linkage": "https://gpbv.omgeving.vlaanderen.be/gpbv-register-beheer/installatiefiche/BE.VL.000000002.INSTALLATION"
    }],
    "locationInfo": [{
      "address": {
        "country": "Belgium",
        "deliveryPoint": "Voortstraat 27, 2400 Mol",
        "electronicMailAddress": "NA"
      },
      "phone": {
        "number": "NA"
      }
    }],
    "alternateName": {
      "name": "BE.VL.000000002.INSTALLATION"
    },
    "note": "Toeristische regio: Kust",
    "categories": [{
      "categoryType": "Type",
      "value": "MineraleIndustrie"
    }, {
      "categoryType": "Category",
      "value": "GPBVInstallatiesIndustrie"
    }, {
      "categoryType": "Theme",
      "value": "NatuurEnMilieu"
    }]
  }
}
```
## POI Attributes Used

### Standard POI Attributes
- **type**: "Feature"
- **geometry**:
  - **type**: "Point"
  - **coordinates**: [51.19391876816891, 5.1644166129636519]
- **featureID**: "c3bf1a5e-df00-4c93-89de-6b0e44e97806"
- **name**:
  - **name**: "AGC Glass Europe Mol"
- **contactInfo**:
  - **role**: "owner"
  - **party**:
    - **contactInfo**:
      - **OnlineResource**: "https://omgeving.vlaanderen.be/gpbv-installaties"
    - **name**: "Afdeling Gebiedsontwikkeling, Omgevingsplanning en -projecten (GOP)"
- **hasMetadata**:
  - **href**: "https://www.vlaanderen.be/datavindplaats/catalogus/gpbv-installaties-in-vlaanderen-in-het-kader-van-de-richtlijn-industriele-emissies-rie-via-poi-service"
  - **rel**: "about"
- **rights**:
  - **otherConstraints**: "Modellicentie_Gratis_Hergebruik"

### Payload Attributes
- **hasPayload**:
  - **usesSchema**:
    - **href**: "https://genpoijson.org/schema/publicationpoi.json"
    - **rel**: "describedby"
  - **onlineResources**:
    - **description**: "Meer info over de installatie, waaronder de vergunningsbesluiten"
    - **linkage**: "https://gpbv.omgeving.vlaanderen.be/gpbv-register-beheer/installatiefiche/BE.VL.000000002.INSTALLATION"
  - **locationInfo**:
    - **address**:
      - **country**: "Belgium"
      - **deliveryPoint**: "Voortstraat 27, 2400 Mol"
      - **electronicMailAddress**: "NA"
    - **phone**:
      - **number**: "NA"
  - **alternateName**:
    - **name**: "BE.VL.000000002.INSTALLATION"
  - **note**: "Toeristische regio: Kust"
  - **categories**:
    - **categoryType**: "Type"
      - **value**: "MineraleIndustrie"
    - **categoryType**: "Category"
      - **value**: "GPBVInstallatiesIndustrie"
    - **categoryType**: "Theme"
      - **value**: "NatuurEnMilieu"
