[[public_poi_interchange_use_case_section]]
== Public POI Interchange Use Case

=== Use Case Overview

The *Public POI Interchange* use case is where there is a desire to have different organizations be able to share information about _Public POIs_.
A public POI is a POI that some of the general public might be interested in going to.
Examples of public POIs are: stores, service businesses, hotels, schools and other government buildings, medical centers, parks, sports centers, etc.

Some organizations gather comprehensive lists of public POIs, perhaps restricted to certain geographies or types of POIs. These organizations are typically vendors of POI information (they used to be called "Yellow Page publishers") or government or trade organizations.

Other organizations consume lists of public POIs, in an effort to develop a globally comprehensive database of public POIs. Such organizations are typically providers of apps or web interfaces that allow consumers to search for, choose among, and perhaps get directions to a public POI that they want to or need to visit. In order to help consumers accomplish these things, the database commonly needs location, contact information, categorical information, open hours, and other attributes, for the POIs.

The above-described organizations would like to be able to exchange or transfer lists of POIs, and merge them together.

The POI-CM standard specifies a way to represent a POI with its name, and its (latitude, longitude) position on earth. The rest of the information needed will have to be specified using non-standard attributes, as described in the xref:06-nonstandard-attributes.adoc#ug_nonstandard_attributes_section[Nonstandard Attributes] section.

=== Nonstandard Attributes for Restaurant POIs

The most important nonstandard attributes needed for the Public POI Interchange use case are:

* xref:06-nonstandard-attributes.adoc#_address[Address]
* xref:06-nonstandard-attributes.adoc#_telephone_number[Telephone Number]
* xref:06-nonstandard-attributes.adoc#_opening_hours[Opening Hours]
* xref:06-nonstandard-attributes.adoc#_category[Category]
* Website

The recommended way to represent the first four of these was discussed in the xref:06-nonstandard-attributes.adoc#ug_nonstandard_attributes_section[Nonstandard Attributes] section.
Website is intended to be the "authoritative" web page for the restaurant in question -- that is, the page that the restaurant would like users to visit if they want to learn more about their restaurant. That web page might answer many of the other attribute questions (e.g., "has a bar") in the list of the previous section.
While one could use the *CI_Contact* type from the informative annex, a simpler recommendation is to extend the schema like by adding this:

[source.JSON]
----
   "Website" {
      "url" : "CharacterString[1..1]"
   }
----

where the *url* value is a Uniform Resource Locator.

=== Multilingual Support ===

While sometimes the lists of POIs being exchanged will be restricted to a known and common language, most examples of this use case will involve multinational POIs; even within a single country, there are often multiple official and unofficial languages spoken.
The ultimate consumers of the data probably want to search and view the information using their own choice of language.

Most of the attributes for public POIs need some extension beyond what has been recommended above in order to allow multiple versions of some strings, each with a labeled language. A recommendation for such an internationalized string is the following:

.Recommended International String Schema
[source,json]
----
    "InternationalString": {
      "text": "CharacterString" [1..1],
      "language": "CharacterString" [0..1]
    }
----

Given the above, there are two places where such a string might be used in the payload: name and address.
The name can simply be a list of one or more names, each with a language code.
It is recommended that if there is more than one name, then each name should have a language and no language should be repeated.

.Recommended International Name Schema
[source,json]
----
    "InternationalName": {
      "name": "InternationalString" [1..],
    }
----


=== Example ===

Putting it all together, here is an example of a restaurant POI using JSON.

.Restaurant POI (JSON)
[source.JSON]
----
{
  "type": "Feature",
  "geometry" : {
    "type" : "Point",
    "coordinates" : [
      45.1491802,
      -84.6907891
    ]
  },
  "featureID" : 693842,
  "name" : {
    "name" : "Chez Jacques"
  },
  "hasPayload" : [
    "usesSchema" : [
      {
        "href" : "https://genpoijson.org/schema/interchangepoi.json",
        "rel" : "describedby"
      }
    ],
    "website" : {
        "url" : "http://chezjacquesrestaurant.com"
    },
    "telephoneNumber" : {
      "number" : "+13205555555"
    },
    "address" : {
      "deliveryPoint" : "400 Atlantic Ave",
      "city" : "Grove City",
      "administrativeArea" : "Minnesota",
      "postalCode" : "56243"
    },
    "category" : {
      "category" : "French Restaurant",
      "categorySystem" : "custom"
    },
    "openingHours" : {
      "openingHoursLines" : [
        "line" : "Mo-Fr 12:00-20:00",
        "line" : "Sa 12:00-22:00"
      ],
      "openingHoursFormat" : "schemadotorg"
    }
  ]
}
----

The schema referenced in *hasPayload* might point to a JSON schema like this:

.Schema for the Restaurant POI (JSON)
[source,json]
----
{
  "$schema": "http://json-schema.org/draft/2020-12/schema#",
  "$id": "https://genpoijson.org/schema/interchangepoi.json",
  "title": "Generic POI Payload for POI Interchange",
  "type" : "object",
  "properties": {
    "telephoneNumber": {
      "type": "object",
      "properties": {
        "number": {"type": "string"},
        "numberType": {"type": "string"}
      },
      "required": [ "number" ]
    },
    "address" : {
      "type": "object",
      "properties": {
        "administrativeArea": {"type": "string"},
        "city": {"type": "string"},
        "country": {"type": "string"},
        "deliveryPoint": {"type": "string"},
        "email": {"type": "string"},
        "postalCode": {"type": "string"}
      }
    },
    "category" : {
      "type": "object",
      "properties": {
        "category": { "type": "string"},
        "categorySystem": {
          "enum" : [ "naics", "osm", "ogcindoor", "geonames", "custom" ]
        }
      },
      "required": [ "category" ]
    },
    "openingHours" : {
      "type": "object",
      "properties": {
        "openingHoursLines": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "openingHoursFormat": {
          "enum" : [ "schemadotorg", "icalendaravailability" ]
        }
      }
    },
    "website" : {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [ "url" ]
    }
  }
}
----

There is no "hasDefinition" property in the Payload. If there were, it could reference a text file with a form of the commentary in this section.
