[[use-case-smart_tourism]]
=== Smart Tourism

*Contributed By:* Timo Ruohomäki, Forum Virium Helsinki Oy

*Motivation:* Provide better and up-to-date information services for tourists

*Summary* 

Smart Tourism is the type of tourism that depends on high level of integration with information systems, possibly in combination with social connections and human interest. Tourism services have a strong link to spatial information systems in providing information on tourist attractions and planning routes between them. The information on tourist attractions can be somewhat dynamic, including opening hours and physical accessibility. Oftentimes with the help of social media services, rating and feedback from visitors is linked to the attractions. The tourism is international by definition, so the information is to be provided in many languages.

<<use-case-smart_tourism-detail,Click to view>> full use case description

*Related Use Cases* 

<Identify any use cases which are related to this one and describe the nature of that relation. Include a hyperlink to each use case.>

*Roles:* 

<List all stakeholders that are involved in the use case. Stakeholders are described in the <<stakeholders-section,Stakeholders Section>> of this document. Each listed stakeholder should be hyperlinked to its description.>

*Devices:* 

<List the target devices, e.g. as a sensor, solar panel, air conditioner>

*Data:* 

<List the type of expected data, e.g. weather and climate data, medical conditions, machine sensors, vehicle data>

*Dependencies:* 

<Identify any dependencies of this use case. Dependencies are described in the <<bibliography-section,Bibliography>> and  <<terms-and-definitions-section,Terms and Definitions>> sections of this document. Each listed dependency should be hyperlinked to its description.>

*Requirements:* 

<Identify the requirements derived from this use case. Requirements are described in the <<requirements-section,Requirements section>> of this document. Each listed requirement should be hyperlinked to its description.>

*Variants:* 

<Describe possible use case variants, if applicable>

*Security Considerations:* 

<Describe any issues related to security; if there are none, say "none" and justify>

*Privacy Considerations:*

<Describe any issues related to privacy; if there are none, say "none" and justify>

*Comments:*
