:Title: OGC Points of Interest Standard Working Group Charter
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <yyyy-mm-dd>
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    YY-nnnrx
|Category: OGC(R) Standards Working Group Charter
|Authors:   <Name(s) of Editor or Editors>
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) <year> Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

To: OGC members & interested parties

A dormant OGC Standards Working Group is being rechartered. The OGC members listed below propose to restart the POI Standards Working Group.  The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual
member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

The purpose of the POI SWG is to produce a version 1.0 encoding standard of points of interest data that includes an abstract data model and JSON implementations of that data model.

Upon completion of the draft the SWG will verify compliance with the OGC Base

=== Definition of Points of Interest
A “point of interest” (PoI) is a location for which information is available. A PoI can be as simple as a set of coordinates, a name and a unique identifier, or more complex such as a three-dimensional model of a building with names in multiple languages information about opening and closing hours and a civic address.

=== PoI Use Cases
There are numerous use cases for PoI. They include location-based social networking,games, assessments of gaps or needs, mapping and navigation systems.

End users may search databases of PoIs to identify properties for sale, financial institutions, accommodations, retail shops, or  transportation. There are also numerous ways the public sector can use PoI. For example, government agencies can provide information to citizens about services and locations by publishing their PoI datasets.

== Business Value Proposition

There are many advantages to standardizing PoI.

First, complying with a standard permits systems to populate a PoI database regardless of authoring platform or application, without transcoding, delays or costs that are incurred when data is compiled from many different contributors using proprietary formats.

Further, with a standard encoding, PoIs can be stored in non-proprietary formats and technology providers can focus on the competitive advantages of faster querying technologies.

When PoI publishers support a standard PoI format, they will be able to sell and transmit PoI data to the applications of the user's choice, regardless of devices, and thereby focus on the value of the dataset, not the development and maintenance of prorietary applications or interfaces.

Finally, when PoI are encoded in compliance with a standard, third parties are able to compile PoI sets from multiple, diverse sources, to compare PoI across sources and services, and to archive PoI without loss of accuracy, metadata or value.

These advantages will offer new value across many use cases.


== Scope of Work

The PoI SWG shall review  and, if deemed appropriate, edit and expand upon the draft specification previously begun in this SWG with a special emphasis on ways to modernize and adopt the most current OGC practices, industry conventions and developer tools to define an information model and data encoding(s).

The items that need to be addressed by the SWG include:

.	Update to conform to the latest OGC document directives. While not mandated for an encoding specification the SWG will conform to the Modular Specifications Policy  as appropriate.
.	Add a JSON encoding with particular attention paid to support ways to build resilient and scalable PoI architectures including but not limited to DGGS and OGC APIs
.	Provide an abstract and/or conformance  test suite.
.	Validate all schemas and examples.
.	Prepare and publish a user guide in compliance with OGC policies.
.	Study the interactions between service model and data encoding approaches to POI and gazetteer functions.
.	Address any other technical and/or editorial issues that arise during the review period.

Change requests and comments submitted through GitHub as well as through traditional processes identified in the OGC Policy and Procedures shall be discussed and addressed by the SWG. 

NOTE: For a SWG focused on revisions to an existing adopted Standard, the SOW should include a statement that the SWG will collect all outstanding Change Request Proposals (CRPs), evaluate each of the proposals, and make edits to the Standard based on CRPs and related decisions of the SWG membership. The SWG, at their discretion, may also ask the membership for any additional change requests that have not been previous submitted. Again, the final deliverable of a revision focused SWG SHALL be a revision of the candidate Standard for consideration by the membership for adoption.

In all cases, the SWG Charter shall provide a basic timeline plan for their activities.


== Statement of relationship of planned work to the current OGC Standards baseline

////
This section describes the relationship of the proposed standards activity to the existing Standards baseline. For the 3 cases:
If defining a new Standard, a statement of the relationship to the existing Standards baseline including statements related to overlap (if any) with existing OGC Standards functionality, harmonization issues, and so forth.

If processing change requests and performing a revision to an existing Standard, a simple statement to this effect shall be made.

If processing a draft submission of a specification developed outside the OGC process, a clear statement of the relationship to the existing Standards baseline including statements related to overlap (if any) with existing OGC Standards functionality, harmonization issues, and so forth. This information is provided to allow a focus of the discussion on criteria for considering any new solution that may be incompatible with older ones, overlaps existing functionality in the current baseline, and criteria for either deprecating older solutions, or simultaneously endorsing more than one option.
////

== What is Out of Scope?

////
A short description of any activities that will be out of scope for the SWG. For example, a SWG may limit consideration of CRPs after a specified date or milestone.
////

== Specific Existing Work Used as Starting Point

The PoI SWG will use the prior draft PoI encoding specification as its starting point.

== Is This a Persistent SWG

[x] YES

[ ] NO

== When can the SWG be Inactivated

////
If this is not a persistent SWG, please define the criteria for determining when the SWG can be inactivated and the project archived. Please note that completion and archiving ensures that all files, wikis, emails, and so forth are archived and available for future viewing and use.
////

== Description of Deliverables

There shall be two deliverables:
•	Points of Interest (PoI) Information Model and JSON Encoding Specification version 1.0, and
•	PoI Standard Users Guide

=== Additional SWG Tasks

////
Describe each additional Standard to be developed by the SWG as an additional task after the deliverables from the initial charter have been completed. This section is blank in a new charter, then is populated with each task approval request per the OGC TC Policies and Procedures.
////

== IPR Policy for this SWG

[x] RAND-Royalty Free

[ ] RAND for fee

== Anticipated Audience / Participants

The target audiences for this SWG and the specification include any organization that has requirements for compiling, sharing, analyzing, publishing or providing PoI data on a public, private or commercial basis. Such organizations include providers of navigation data, business information, health data, emergency response data, real estate data, historical place names, and government agencies.

== Domain Working Group Endorsement

////
The SWG will list all Domain Working Groups (DWGs) in which the SWG formation was discussed and/or chartered. If a DWG has specifically endorsed the formation of the SWG, then a statement of endorsement should be included.
////

== Other informative information about the work of this SWG

=== Collaboration

The PoI SWG will perform its work in public in a GitHub repository operated by the PoI SWG.

=== Similar or Applicable Standards Work (OGC and Elsewhere)

////
The following Standards and projects may be relevant to the SWG's planned work, although none currently provide the functionality anticipated by this committee's deliverables:

OASIS BPEL
IETF HTTP

The SWG intends to seek and if possible maintain liaison with each of the organizations maintaining the above works.
////

=== Details of first meeting

////
Example:
The first meeting of the SWG will be held by telephone conference call at 10AM EDT on 1 October 2007. Call-in information will be provided to the SWG's e-mail list and on the portal calendar in advance of the meeting.
////

=== Projected on-going meeting schedule

////
Example:
The work of the SWG will be carried out primarily by email and conference calls, possibly every two weeks, with face-to-face meetings perhaps at each of the OGC TC meetings.
////

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page. Extend the table as necessary.

|===
|Name |Organization
| |
|===

=== Conveners

////
Name of individual(s) who started the SWG process. Could be the lead for an RFC submission, an OGC staff person, or an individual who believes it is time for a revision to an adopted Standard.
////

== References

////
Optional list of references.
////
