:Title: OGC Points of Interest Standard Working Group Charter
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <2021-03-04>
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    21-012
|Category: OGC(R) Standards Working Group Charter
|Authors:   Marna Roos (AfriGIS), Christine Perey (OARC)
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2021 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

To: OGC members & interested parties

A dormant OGC Standards Working Group is being rechartered. The OGC members listed below propose to restart the Points of Interest (PoI) Standards Working Group.  The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual
member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

The purpose of the Points of Interest (PoI) SWG is to produce a version 1.0 encoding standard of points of interest data that includes an abstract data model and JSON implementations of that data model.

Upon completion of the draft, the SWG will verify compliance with the OGC Baseline.

=== Definition of Points of Interest
A “point of interest” (PoI) is a location for which information is available. A PoI can be as simple as a set of coordinates, a name and a unique identifier, or more complex such as a three-dimensional model of a building with names in multiple languages information about opening and closing hours, and a civic address.

=== PoI Use Cases
There are numerous use cases for PoI. They include location-based social networking, games, assessments of gaps or needs, mapping and navigation systems, etc.

End users may search databases of PoIs to identify properties for sale, financial institutions, accommodations, retail shops, or transportation. There are also numerous ways the public sector can use PoI data. For example, government agencies can provide information to citizens about services and locations by publishing their PoI datasets.

== Business Value Proposition

There are many advantages to standardizing PoI.

The first goal of the PoI standard is *interoperable PoI data and systems.* Complying with this standard will permit systems that populate a PoI database regardless of authoring platform or application, to do so without transcoding, delays or costs that are incurred when data is compiled from many different contributors using proprietary formats.

Further, with a standard encoding, PoIs can be stored in open, non-proprietary formats and technology providers can focus on their respective competitive advantages.

When PoI publishers support this PoI standard, they will be able to make available PoI data and to transmit the data to the *applications of the user's choice,* regardless of devices, and thereby focus on the *value of the data*, not the development and maintenance of proprietary applications or interfaces.

Furthermore, when data are encoded in compliance with the PoI standard, third parties are able to *create, interact with, and query* across platforms from multiple, diverse sources, to *compare, merge, and, at the end of life cycle, to archive*, PoI without loss of accuracy, metadata or value.

These advantages will offer new value across many use cases.

Finally, as a result of higher confidence in PoI data quality, validity and security, a widely adopted PoI standard will *increase use of and trust in PoI*, in general.

== Scope of Work

The PoI SWG shall review  and, if deemed appropriate, edit and expand upon the draft specification previously begun in this SWG with a special emphasis on ways to modernize and adopt the most current OGC practices, industry conventions, and developer tools to define an information model and data encoding(s).

The items may be addressed by the SWG include the following:

.	Update to conform to the latest OGC document directives. While not mandated for an encoding specification, the SWG will conform to the Modular Specifications Policy  as appropriate.
.	Add a JSON encoding with particular attention paid to support ways to build resilient and scalable PoI architectures.
. Study PoI use cases to identify their needs for data granularity, resolution, metadata and other requirements and determine the relevance of these requirements to meeting the standard's goals.
.	Address any technical and/or editorial issues that arise during the review period.
. Address change requests and comments submitted to the SWG through GitHub.
. Provide an abstract and/or conformance test suite.
.	Validate all schemas and examples.
.	Prepare and publish a user guide in compliance with OGC policies.

The PoI SWG anticipates completing the first deliverable, a Points of Interest (PoI) Information Model and JSON Encoding Specification version 1.0 standard, in 18 months. The SWG will then prepare the second deliverable, the POI User Guide, in the following 6 months.

== Statement of relationship of planned work to the current OGC Standards baseline

The SWG will examine whether the proposed standard maintains interoperability with the OGC Standards Baseline and assess whether extension of existing standards could achieve the goals of PoI SWG.

The SWG will also explore the need to develop additional PoI related standards to better support the use cases explored in the objectives as specified in the Scope of Work.

== What is Out of Scope?

This standard will not define or in any way be limited to a web services environment.

This SWG will not define or become a PoI registry or library.

== Specific Existing Work Used as Starting Point

The PoI SWG will use the prior draft PoI encoding specification as its starting point.

== Is This a Persistent SWG

[x] YES

[ ] NO

== Description of Deliverables

There shall be two deliverables:

•	Points of Interest (PoI) Information Model and JSON Encoding Specification version 1.0, and
•	PoI Standard Users Guide

== IPR Policy for this SWG

[x] RAND-Royalty Free

[ ] RAND for fee

== Anticipated Audience / Participants

The target audiences for this SWG and the specification include any organization that has requirements for creating, interacting, compiling, sharing, analyzing, publishing, or providing PoI data on a public, private or commercial basis.

Such organizations include providers of navigation data, business information, health data, emergency response data, real estate data, historical place names, and government agencies.

== Other informative information about the work of this SWG

=== Collaboration

The PoI SWG will perform its work in public in a GitHub repository operated by OGC and managed by the PoI SWG chairs.

=== Similar or Applicable Standards Work (OGC and Elsewhere)

==== World Wide Web Consortium POI Working Group
The starting point for this implementation standard shall be prior work begun, but abandoned, by the W3C with OGC participation, described at http://www.w3.org/2010/POI/. This effort generally conforms to the ISO information model as described in 19112 (see below), although it has fewer required properties, and extends that model in some very important ways that reflect its focus on the architecture of the Web. In terms of similarities with the ISO and OGC standards, PoI’s primary properties for gazetteer items are a name and a geographic identifier (location) that can be either direct, indirect, or both. The draft PoI specification expanded upon this model with a mandatory URI-based globally unique ID, along with Categories and Links.

==== Schema.org/Place
Place is a Schema.org type for entities that have a somewhat fixed, physical extension. In addition to the generic profile for places, fields and metadata for more specific place types, such as accommodation, administrative area, civic structure, landform, landmarks or historical buildings, local businesses, residence, tourist attraction and tourist destination, have been published.

==== ISO 19112 – Spatial referencing by geographic identifiers
ISO 19112 describes a basic framework for describing items in a gazetteer. It links “indirect” geographic references, which are things like addresses and town names, to “direct” references, which are geographic coordinates. In other words, ISO 19112 defines a standard information model for saying that a place is located at a specific position on the Earth. The standard goes far beyond that baseline though. Positions on the Earth can be described in any number of ways, such as by a rough bounding box, an exact polygon boundary, or a point in the center of the place. ISO 19112 also describes a host of metadata that can be associated with the place, such as the administrative agency responsible for the data, in what part of the world the data should be used, and in what time period it’s valid.

==== ISO 19155:2012 – Place identifier
In ISO 19155, the identifier of a place is referred to as a Place Identifier (PI). A single “place” may be identified using several separate Place Identifiers.

Place descriptions are used for information retrieval. In reality, those identifiers often refer to the same place. Currently these relationships are difficult for machines to correctly distinguish, which impedes the discovery and retrieval of information. The conceptual architecture and reference model defined in ISO 19155 provides a mechanism for solving these problems.

When implemented, this architecture would enable the access and sharing of place descriptions using the Place Identifier as the standardized method.

Within the reference model, place descriptions are defined using a PI. A PI consists of a reference system (RS), a value, and the valid temporal period of that value.

=== Details of first meeting

The first meeting of the SWG will be held by telephone conference call at 11 AM EDT on 24 March 2021. Call-in information will be provided to the SWG's e-mail list and on the portal calendar in advance of the meeting.

=== Projected on-going meeting schedule

The work of the SWG will be carried out primarily by email and conference calls, every two weeks, with possible face-to-face meetings at each of the OGC member meetings.

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed.

|===
|Name |Organization
|Marna Roos | AfriGIS
|Christine Perey | Open AR Cloud (PEREY Research & Consulting)
|Felix Cheung | PlaceKey
|Matthew Purss | Panagea Innovations
|Clemens Portele | Interactive Instruments

|===

=== Conveners

|===
|Name |Organization
|Marna Roos | AfriGIS
|Christine Perey | Open AR Cloud (PEREY Research & Consulting)
|Felix Cheung | PlaceKey
|Matthew Purss | Panagea Innovations
|Kyoung-sook Kim | AIST
|Sisi Zlatanova | University of New South Wales


|===

== References

////
Optional list of references.
////
