[appendix,obligation="informative"]
[heading='terms and definitions']
[[glossary]]
== Glossary

[[application-schema-definition]] 
=== application schema:: 

_conceptual schema_ (<<conceptual-schema-definition>>) for data required by one or more applications. 

NOTE: An _application schema_ (<<application-schema-definition>>) contains selected parts of the base schemas presented in the ORM Information Viewpoint.

NOTE: Designers of _application schemas_ (<<application-schema-definition>>) may extend or restrict the types defined in the base schemas to define appropriate types for an application _domain_ (<<domain-definition>>). 

NOTE: _Application schemas_ (<<application-schema-definition>>) are information models for a specific information community.

[.source]
<<ISO19101-1,clause 4.1.2>>, OGC Definitions Register at http://www.opengis.net/def/glossary/term/ApplicationSchema

[[attribute-definition]]
=== attribute::

named _property_ (<<property-definition>>) of an entity

NOTE: Describes a geometrical, topological, thematic, or other characteristic of an entity.

[.source]
<<ISO2382,clause 2121440>>

[[conceptual-schema-definition]] 
=== conceptual schema::

. formal description of a _conceptual model_ (<<conceptual-model-definition>>) [ISO 19101-1:2014, 4.1.6]
. base schema. Formal description of the model of any geospatial information. _Application schemas_ (<<application-schema-definition>>) are built from _conceptual schemas_ (<<conceptual-schema-definition>>).

[.source]
<<ogcdr,OGC Definitions Register>>

[[coordinate-definition]]
=== coordinate::

one of a sequence of numbers designating the _position_ (<<position-definition>>) of a _point_ (<<point-definition>>)

NOTE: In a spatial _coordinate reference system_ (<<coordinate-reference-system-definition>>), the _coordinate_ (<<coordinate-definition>>) numbers are qualified by units.

[.source]
<<ISO19111,clause 3.1.5>>

[[coordinate-reference-system-definition]]
=== coordinate reference system::

coordinate system that is related to an _object_ (<<object-definition>>) by a _datum_ (<<datum-definition>>)

NOTE: For geodetic and vertical _datums_ (<<datum-definition>>), the _object_ (<<object-definition>>) will be the Earth.

[.source]
<<ISO19111,clause 3.1.9>>

[[coordinate-system-definition]]
=== coordinate system::

set of mathematical rules for specifying how _coordinates_ (<<coordinate-definition>>) are to be assigned to _points_

[.source]
<<ISO19111,clause 3.1.11>>

[[datum-definition]]
=== datum::

parameter or set of parameters that realize the _position_ (<<position-definition>>) of the origin, the scale, and the orientation of a _coordinate system_ (<<coordinate-system-definition>>)

[.source]
<<ISO19111,clause 3.1.15>>

[[direct-position-definition]]
=== direct position::

_position_ (<<position-definition>>) described by a single set of _coordinates_ (<<coordinate-definition>>) within a _coordinate reference system_ (<<coordinate-reference-system-definition>>)

[.source]
<<ISO19136-1,clause 3.1.20>>

[[domain-definition]]
=== domain:: 

well-defined set 

NOTE: _Domains_ (<<domain-definition>>) are used to define the _domain_ (<<domain-definition>>) set and range set of _attributes_ (<<attribute-definition>>), operators and functions.

[.source]
<<ISO19109,clause 4.8>>

=== domain <general vocabulary>::

distinct area of human knowledge to which a terminological entry is assigned 

NOTE: Within a database or other terminology collection, a set of _domains_ (<<domain-definition>>) will generally be defined. More than one _domain_ (<<domain-definition>>) can be associated with a given _concept_ (<<concept-definition>>).

[.source]
<<ISO19104,clause 4.11>>

=== domain <ontology>::

restriction to constrain the subject _class_ (<<class-definition>>) which participates in a subject-predicate-object triple 

[.source]
<<ISO19150-4,clause 3.1.12>>

=== domain <postal address>::

an area in which a set of specific postal address types and postal address renderings is prescribed by postal operators 

[example] 
The most typical example of a postal address _domain_ (<<domain-definition>>) is a country where a designated postal operator provides postal delivery services.

[.source]
<<ISO19160-4,clause 3.14>>

[[geometric-complex-definition]]
=== geometric complex::

set of disjoint _geometric primitives_ (<<geometric-primitive-definition>>) where the boundary of each _geometric primitive_ (<<geometric-primitive-definition>>) can be represented as the union of other _geometric primitives_ (<<geometric-primitive-definition>>) of smaller dimensions within the same set

[.source]
<<ISO19107,clause 3.47>>

[[geometric-object-definition]]
=== geometric object::

spatial _object_ (<<object-definition>>) representing a _geometric set_ (<<geometric-set-definition>>)

NOTE: A _geometric object_ consists of a _geometric primitive_, a collection of _geometric primitives_, or a _geometric complex_ treated as a single entity. A _geometric object_ may be the spatial representation of an _object_ such as a _feature_ or a significant part of a _feature_.

[.source]
<<ISO19107,clause 3.49>>

[[geometric-primitive-definition]]
=== geometric primitive (geometry)::

_geometric object_ (<<geometric-object-definition>>) representing a single, connected, homogeneous (isotopic) element of space

NOTE: _Geometric primitives_ (<<geometric-primitive-definition>>) are non-decomposed _objects_ (<<object-definition>>) that present information about geometric configuration. They include _points_, curves, surfaces, and solids. Many _geometric objects_ (<<geometric-object-definition>>) behave like primitives (supporting the same interfaces defined for geometric primitives) but are actually composites composed of some number of other primitives. General collections may be aggregates and incapable of acting like a primitive (such as the lines of a complex network, which is not connected and thus incapable of being traceable as a single line). By this definition, a _geometric primitive_ (<<geometric-primitive-definition>>) is topological open, since the boundary _points_ are not isotropic to the interior _points_. Geometry is assumed to be closed. For _points_, the boundary is empty.

[.source]
<<ISO19107,clause 3.50>>

[[geometric-set-definition]]
=== geometric set::

set of _points_ 

[.source]
<<ISO19107,clause 3.53>>

[[location-definition]]
=== location::

particular _place_ (<<place-definition>>) or _position_ (<<position-definition>>)

NOTE: A _location_ (<<location-definition>>) identifies a geographic _place_.

NOTE: _Locations_ (<<location-definition>>) are physically fixed _points_, typically on the surface of the Earth, although _locations_ (<<location-definition>>) can be relative to other, non-earth centric coordinate reference systems. 

NOTE: _Locations_ (<<location-definition>>) can be a single _point_, a centroid, a minimum bounding rectangle, or a set of vectors. 

NOTE: A _location_ (<<location-definition>>) should be persistent over time and does not change. 

NOTE: Multiple _POIs_ (<<point-of-interest-definition>>) may share the same _location_ (<<location-definition>>). 

NOTE: When a _POI_ (<<point-of-interest-definition>>) physically moves it is understood to have acquired a new _location_ (<<location-definition>>).

[.source]
<<ISO19112,clause 3.1.3>>

[[metaclass-definition]]
=== metaclass::

a _class_ (<<class-definition>>) whose instances are also _classes_ (<<class-definition>>)

[.source]
<<omguml,clause 22>> Object Management Group (OMG) UML Standard Version 2.5.1

[[object-definition]]
=== object::

entity with a well defined boundary and identity that encapsulates state and behaviour

NOTE: This term was first used in this way in the general theory of object oriented programming, and later adopted for use in this same sense in UML. An _object_ (<<object-definition>>) is an instance of a _class_ (<<class-definition>>). _Attributes_ (<<attribute-definition>>) and relationships represent state. _Operations_ (<<operation-definition>>), methods, and state machines represent behavior.

[.source]
<<OMG/UML UML Semantics, version 1.3, 1997.>>

[[operation-definition]]
=== operation::

specification of a transformation or query that an _object_ (<<object-definition>>) may be called to execute

NOTE: An _operation_ (<<operation-definition>>) has a name and a list of parameters.

NOTE: See <<ISO19119,clause 7.2>> for a discussion of _operation_ (<<operation-definition>>)

[.source]
<<ISO19119,clause 4.1.10>>

[[place-definition]]
=== place::

identifiable part of any space

[.source]
<<ISO19155,clause 4.8>>

[[platform-definition]] 
=== Platform (Model Driven Architecture)::

the set of resources on which a system is realized.

[.source]
<<mdaguide>>, 
#Object Management Group, Model Driven Architecture Guide rev. 2.0#

[[point-definition]]
=== point::

0-dimensional geometric primitive, representing a _position_ (<<position-definition>>)

[.source]
<<ISO19136-1,clause 3.1.47>>

[[point-of-interest-definition]]
=== point of interest::

alt:[POI]

_location_ (<<location-definition>>) where one can find a _place_, product or service

NOTE: A _POI_ (<<point-of-interest-definition>>) is typically identified by _name_ rather than by an _address_.

NOTE: A _POI_ (<<point-of-interest-definition>>) is characterized by _type_, which may be used as a reference _point_ or a target in a _location_ (<<location-definition>>) based service request.

NOTE: A _POI_ (<<point-of-interest-definition>>) does not exclude the labeling, identification, and tracking of persons and other physical _objects_ (<<object-definition>>) that have no permanent _location_ (<<location-definition>>).

[example]
destination of a route; such as, Boston

[[position-definition]]
=== position::

data type that describes a _point_ or _geometry_ potentially occupied by an _object_ (<<object-definition>>) or person

NOTE:  A _direct position_ (<<direct-position-definition>>) is a semantic subtype of _position_ (<<position-definition>>). _Direct positions_ (<<direct-position-definition>>) as described can only define a _point_, and therefore not all _positions_ (<<position-definition>>) can be represented by a _direct position_ (<<direct-position-definition>>). That is consistent with the is type of relation. An ISO 19107 geometry is also a _position_ (<<position-definition>>), but not a _direct position_ (<<direct-position-definition>>)

[.source]
<<ISO19133>>

[[property-definition]]
=== property::

facet or _attribute_ (<<attribute-definition>>) of an _object_ (<<object-definition>>) referenced by a name

[example]
Abby's car has the colour red, where "colour red" is a _property_ (<<property-definition>>) of the car.

[.source]
<<ISO19143,clause 4.21>>, Note 1 to entry has been added from ISO 19156, 4.15

