[appendix]
[[iso_data_dictionary_section]]
== ISO Data Dictionary

ISO Technical Committee 211 maintains a harmonized UML model which covers many of their standards. All of the TC211 Standards which are relevant to the POI Standard are included. Therefore the full UML model for POI consists of the classes defined in the POI UML model as well as those which referenced from the TC211 Hamonized UML model.

The Data Dictionary tables in this section were software generated from the TC211 Hamonized UML model. As such, this section provides a normative representation of the TC211 classes which are leveraged by the POI Conceptual Model.

Note that some of the properties in the ISO model are not populated. Since the model is normative, the missing information cannot be included in this document until it is first included in the ISO model by TC211.

=== General Feature Model 
The following classes are defined in <<ISO19109,(ISO 19109:2015)>>

[[AnyFeature-section]]
.Any Feature Class
[cols="1a"]
|===
|*AnyFeature* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! The class AnyFeature is
an instance of the «metaclass» FeatureType (ISO 19109). It represents the set
of all classes which are feature types. +
+ 
In an implementation this abstract class shall be substituted by a concrete class representing a feature type from an application schema associated with a domain of discourse (ISO 19109, ISO 19101). 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} !<<FeatureType-section,FeatureType>> [1..1] !
!===
|===

[[FeatureType-section]]
.Feature Type Class
[cols="1a"]
|===
|*FeatureType* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! feature: abstraction of real world phenomena +
NOTE: A feature may occur as a type or an instance. Feature type or feature instance should be used when only one is meant. +
This class describes how a feature class shall be constructed in an Application Schema. In accordance with the conformance clause of the standard, instances of this class are instanciated as feature classes in an Application Schema
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! IdentifiedType 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «Metaclass»
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! name is mandatory (Invariant):     
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity* !*Definition*
!{set:cellbgcolor:#FFFFFF}  ! NS_AvoidList  [0..*] !
!{set:cellbgcolor:#FFFFFF} superType  ! <<FeatureType-section,FeatureType>>   [0..*] !
!{set:cellbgcolor:#FFFFFF} featureTypeMetadata  ! MD_Metadata   [0..*] !
!{set:cellbgcolor:#FFFFFF} carrierOfCharacteristics  ! PropertyType   [0..*] !
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
!{set:cellbgcolor:#FFFFFF} isAbstract   !Boolean  !
!===
|===

=== Geometry
The following classes are defined in <<ISO19107,(ISO 19107:2003)>>

[[GM_Object-section]]
.GM_Object Class
[cols="1a"]
|===
|*GM_Object* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GM_Object is the root class of the geometric object taxonomy and supports interfaces common to all geographically referenced geometric objects. GM_Object instances are sets of direct positions in a particular coordinate reference system. A GM_Object can be regarded as an infinite set of points that satisfies the set operation interfaces for a set of direct positions, TransfiniteSet<DirectPosition>. Since an infinite collection class cannot be implemented directly, a Boolean test for inclusion shall be provided by the GM_Object interface. This international standard concentrates on vector geometry classes, but future work may use GM_Object as a root class without modification.
NOTE As a type, GM_Object does not have a well-defined default state or value representation as a data type. Instantiated subclasses of GM_Object will. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! none 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «type»
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! dimension() >  boundary().dimension (Invariant):     
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! boundary().notEmpty() implies boundary().dimension() = dimension() -1 (Invariant):     
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! boundary().isEmpty() = isCycle() (Invariant):     
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}   !Geometry [1..1]!
!{set:cellbgcolor:#FFFFFF}   !TransfiniteSet<DirectPosition>  [1..1]!
!{set:cellbgcolor:#FFFFFF}   !CV_DomainObject  [1..1]!
!{set:cellbgcolor:#FFFFFF} CRS  !CRS  [0..1]!
!{set:cellbgcolor:#FFFFFF} CRS  !SC_CRS [0..1]!
!===
|=== 

[[GM_Point-section]]
.GM_Point Class
[cols="1a"]
|===
|*GM_Point* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GM_Point is the basic data type for a geometric object consisting of one and only one point.  
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! GM_Primitive 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «type»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}   !Point  [1..1]!
!{set:cellbgcolor:#FFFFFF} composite  !GM_CompositePoint [0..*]!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} position   !DirectPosition [1..1]  !The attribute "position" shall be the DirectPosition of this GM_Point.
GM_Point::position [1] : DirectPosition
NOTE In most cases, the state of a GM_Point is fully determined by its position attribute. The only exception to this is if the GM_Point has been subclassed to provide additional non-geometric information such as symbology.
!===
|=== 

[[GM_LineString-section]]
.GM_LineString Class
[cols="1a"]
|===
|*GM_LineString* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A GM_LineString (Figure 16) consists of sequence of line segments, each having a parameterization like the one for GM_LineSegment (See 6.4.11). The class essentially combines a Sequence<GM_LineSegments> into a single object, with the obvious savings of storage space.
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! GM_Primitive 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «type»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
!{set:cellbgcolor:#FFFFFF} controlPoint   !GM_PointArray [1..1]!
!===
|=== 

[[GM_Polygon-section]]
.GM_Polygon Class
[cols="1a"]
|===
|*GM_Polygon* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A GM_Polygon (Figure 21) is a surface patch that is defined by a set of boundary curves and an underlying surface to which these curves adhere. The default is that the curves are coplanar and the polygon uses planar interpolation in its interior.  
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! GM_Primitive 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «type»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} surface  ! GM_PolyhedralSurface   [0..1] !
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
!{set:cellbgcolor:#FFFFFF} boundary   !GM_SurfaceBoundary  !
!{set:cellbgcolor:#FFFFFF} spanningSurface   !GM_Surface  [0..1] !
!===
|=== 

=== Citation and responsible party information
The following classes are defined in <<ISO19115,(ISO 19115-1 Edition 1)>>

[[CI_Contact-section]]
.CI_Contact Class
[cols="1a"]
|===
|*CI_Contact* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! information required to enable contact with the responsible person and/or organisation 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  None
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} address   !CI_Address  [0..*] !physical and email address at which the organisation or individual may be contacted
 
!{set:cellbgcolor:#FFFFFF} contactInstructions   !<<CharacterString-section,CharacterString>>  [0..1] !supplemental instructions on how or when to contact the individual or organisation
 
!{set:cellbgcolor:#FFFFFF} contactType   !<<CharacterString-section,CharacterString>>  [0..1] !type of contact
 
!{set:cellbgcolor:#FFFFFF} hoursOfService   !<<CharacterString-section,CharacterString>>  [0..*] !time period (including time zone) when individuals can contact the organisation or individual
 
!{set:cellbgcolor:#FFFFFF} onlineResource   !CI_OnlineResource  [0..*] !on-line information that can be used to contact the individual or organisation
 
!{set:cellbgcolor:#FFFFFF} phone   !CI_Telephone  [0..*] !telephone numbers at which the organisation or individual may be contacted
!===
|=== 

[[CI_Individual-section]]
.CI_Individual Class
[cols="1a"]
|===
|*CI_Individual* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! information about the party if the party is an individual 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: !<<CI_Party-section,CI_Party>>
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  None
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! count (name + positionName) > 0 (Invariant):     
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}   ! <<CI_Organisation-section,CI_Organisation>>   [1..1] !
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} positionName   !<<CharacterString-section,CharacterString>>  [0..1] !position of the individual in an organisation
!===
|=== 

[[CI_Organisation-section]]
.CI_Organisation Class
[cols="1a"]
|===
|*CI_Organisation* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! information about the party if the party is an organisation 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: !<<CI_Party-section,CI_Party>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! count (name + logo) > 0 (Invariant):     
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} individual ! <<CI_Individual-section,CI_Individual>> [0..*] !an individual in the named organisation
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} logo   !MD_BrowseGraphic  [0..*] !Graphic identifying organization
!===
|=== 

[[CI_Party-section]]
.CI_Party Class
[cols="1a"]
|===
|*CI_Party* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! information about the individual and/or organisation of the party 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «abstract»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}   ! <<CI_Responsibility-section,CI_Responsibility>>   [] !
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} contactInfo   !<<CI_Contact-section,CI_Contact>>  [0..*] !contact information for the party
 
!{set:cellbgcolor:#FFFFFF} name   !<<CharacterString-section,CharacterString>>  [0..1] !name of the party (individual or organization)
!===
|=== 

[[CI_Responsibility-section]]
.CI_Responsibility Class
[cols="1a"]
|===
|*CI_Responsibility* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! information about the party and their role 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  None
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} party ! <<CI_Party-section,CI_Party>> [1..*] !information about the party
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} extent   !EX_Extent  [0..*] !spatial or temporal extent of the role
 
!{set:cellbgcolor:#FFFFFF} role   !CI_RoleCode [1..1] !function performed by the responsible party
!===
|=== 

=== Constraint information

The following classes are defined in <<ISO19115,(ISO 19115-1 Edition 1)>>

[[MD_Constraints-section]]
[cols="1a"]
|===
|*MD_Constraints* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! restrictions on the access and use of a resource or metadata 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}   ! MD_Identification [] !
!{set:cellbgcolor:#FFFFFF}   ! MD_Metadata [] !
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} constraintApplicationScope   !MD_Scope  [0..1] !Spatial and temporal extent of the application of the constraint restrictions
 
!{set:cellbgcolor:#FFFFFF} graphic   !MD_BrowseGraphic  [0..*] !graphic /symbol indicating the constraint 
 
!{set:cellbgcolor:#FFFFFF} reference   !CI_Citation  [0..*] !citation/URL for the limitation or constraint, eg. copyright statement, license agreement, etc
 
!{set:cellbgcolor:#FFFFFF} releasability   !<<MD_Releasability-section,MD_Releasability>>  [0..1] !information concerning the parties to whom the resource can or cannot be released
 
!{set:cellbgcolor:#FFFFFF} responsibleParty   !<<CI_Responsibility-section,CI_Responsibility>>  [0..*] !party responsible for the resource constraints
 
!{set:cellbgcolor:#FFFFFF} useLimitation   !<<CharacterString-section,CharacterString>>  [0..*] !limitation affecting the fitness for use of the resource or metadata. Example, "not to be used for navigation"
!===
|=== 

[[MD_LegalConstraints-section]]
[cols="1a"]
|===
|*MD_LegalConstraints* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! restrictions and legal prerequisites for accessing and using the resource or metadata 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! otherConstraints: only documented if accessConstraints or useConstraints = "otherRestrictions" (Invariant):     
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! If MD_LegalConstraints used then count of (accessConstraints + useConstraints + otherConstraints + useLimitation + releasability ) > 0 (Invariant):     
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} accessConstraints   !MD_RestrictionCode  [0..*] !access constraints applied to assure the protection of privacy or intellectual property, and any special restrictions or limitations on obtaining the resource or metadata
 
!{set:cellbgcolor:#FFFFFF} otherConstraints   !<<CharacterString-section,CharacterString>>  [0..*] !other restrictions and legal prerequisites for accessing and using the resource or metadata
 
!{set:cellbgcolor:#FFFFFF} useConstraints   !MD_RestrictionCode  [0..*] !constraints applied to assure the protection of privacy or intellectual property, and any special restrictions or limitations or warnings on using the resource or metadata
!===
|=== 

[[MD_Releasability-section]]
[cols="1a"]
|===
|*MD_Releasability* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! information about resource release constraints 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! count (addressee + statement) > 0 (Invariant):     
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} addressee   !<<CI_Responsibility-section,CI_Responsibility>>  [0..*] !party to which the release statement applies
 
!{set:cellbgcolor:#FFFFFF} disseminationConstraints   !MD_RestrictionCode  [0..*] !component in determining releasability
 
!{set:cellbgcolor:#FFFFFF} statement   !<<CharacterString-section,CharacterString>>  [0..1] !release statement
!===
|=== 

[[MD_SecurityConstraints-section]]
[cols="1a"]
|===
|*MD_SecurityConstraints* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! handling restrictions imposed on the resource or metadata for national security or similar security concerns 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} classification   !MD_ClassificationCode  !name of the handling restrictions on the resource or metadata
 
!{set:cellbgcolor:#FFFFFF} classificationSystem   !<<CharacterString-section,CharacterString>>  [0..1] !name of the classification system
 
!{set:cellbgcolor:#FFFFFF} handlingDescription   !<<CharacterString-section,CharacterString>>  [0..1] !additional information about the restrictions on handling the resource or metadata.
!{set:cellbgcolor:#FFFFFF} userNote   !<<CharacterString-section,CharacterString>>  [0..1] !explanation of the application of the legal constraints or other restrictions and legal prerequisites for obtaining and using the resource or metadata
!===
|=== 

=== Identification information
The following classes are defined in <<ISO19115,(ISO 19115-1 Edition 1)>>

[[MD_KeywordClass-section]]
.MD_KeywordClass Class
[cols="1a"]
|===
|*MD_KeywordClass* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! specification of a class to categorize keywords in a domain-specific vocabulary that has a binding to a formal ontology 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  None
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}   ! <<MD_Keywords-section,MD_Keywords>>   [] !
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} className   !<<CharacterString-section,CharacterString>> [1..1]  !character string to label the keyword category in natural language
 
!{set:cellbgcolor:#FFFFFF} conceptIdentifier   !URI  [0..1] !URI of concept in ontology specified by the ontology attribute; this concept is labeled by the className: CharacterString.
 
!{set:cellbgcolor:#FFFFFF} ontology   !CI_Citation [1..1]  !a reference that binds the keyword class to a formal conceptualization of a knowledge domain for use in semantic processingNOTE: Keywords in the associated MD_Keywords keyword list must be within the scope of this ontology
!===
|=== 

[[MD_Keywords-section]]
.MD_Keywords Class
[cols="1a"]
|===
|*MD_Keywords* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! keywords, their type and reference source NOTE: When the resource described is a service, one instance of MD_Keyword shall refer to the service taxonomy defined in ISO 19119, 8.3) 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! When the resource described is a service, one instance of MD_Keyword shall refer to the service taxonomy defined in ISO 19119 (Invariant):     
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}   ! MD_Identification [] !
!{set:cellbgcolor:#FFFFFF} keywordClass  ! <<MD_KeywordClass-section,MD_KeywordClass>>   [0..1] !association of a MD_Keywords instance with a MD_KeywordClass to provide user-defined categorization of groups of keywords that extend or are orthogonal to the standardized KeywordTypeCodes and are associated with an ontology that allows additional semantic query processing
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} keyword   !<<CharacterString-section,CharacterString>>  [1..*] !commonly used word(s) or formalised word(s) or phrase(s) used to describe the subject
 
!{set:cellbgcolor:#FFFFFF} thesaurusName   !CI_Citation [0..1] !name of the formally registered thesaurus or a similar authoritative source of keywords
 
!{set:cellbgcolor:#FFFFFF} type   !MD_KeywordTypeCode [0..1] !subject matter used to group similar keywords
!===
|=== 

=== Name types
The following classes are defined in <<ISO19103,(ISO 19103:2015)>>

[[GenericName-section]]
.Generic Name Class
[cols="1a"]
|===
|*GenericName* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! Generic Name is the abstract class for all names in a NameSpace. Each instance of a GenericName is either a LocalName or a ScopedName. A LocalName references a local object directly accessible from the NameSpace. A ScopedName is a composite of a LocalName for locating another NameSpace and a GenericName valid in that NameSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  interface
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} scope  ! <<NameSpace-section,NameSpace>>   [1..1] !
!===
|=== 

[[LocalName-section]]
.Local Name Class
[cols="1a"]
|===
|*LocalName* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A LocalName references a local object directly accessible from the NameSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<GenericName-section,GenericName>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! interface 
!===
|=== 

[[MemberName-section]]
.Member Name Class
[cols="1a"]
|===
|*MemberName* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A MemberName is a LocalName that references either an attribute slot in a record or  recordType or an attribute, operation, or association role in an object instance or  type description in some form of schema.  
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<LocalName-section,LocalName>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! interface 
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} aName   !<<CharacterString-section,CharacterString>> [1..1]  !The stored value "aName" is the returned value for the "aName()" operation.  
 
!{set:cellbgcolor:#FFFFFF} attributeType   !<<TypeName-section,TypeName>> [1..1] !The allowable type for this member.  
!===
|=== 

[[NameSpace-section]]
.Namespace Class
[cols="1a"]
|===
|*NameSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Name Space is a domain in which "names" given by character strings (possibly under local constrains constraints enforced by the Name Space) can be mapped to objects via a getObejct operation. Examples include objects which form a Name Space for their attributes, operations and associations, or Schemas that form Name Spaces for their included data types or classes. 
Not all methods for NameSpaces need to be made publicly accessible. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! interface 
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} name  ! <<GenericName-section,GenericName>>   [0..*] !
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} acceptableClassList   !<<TypeName-section,TypeName>> [1..1] !
 
!{set:cellbgcolor:#FFFFFF} isGlobal   !Boolean [1..1] !
!===
|=== 

[[ScopedName-section]]
.Scoped Name Class
[cols="1a"]
|===
|*ScopedName* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! ScopedName is a composite of a LocalName for locating another NameSpace and a GenericName valid in that NameSpace. ScopedName contains a LocalName as head and a GenericName, which might be a LocalName or a ScopedName, as tail. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<GenericName-section,GenericName>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! interface 
!===
|=== 

[[TypeName-section]]
.Type Name Class
[cols="1a"]
|===
|*TypeName* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A TypeName is a LocalName that references either a recordType or object type in some form of schema. The stored value "aName" is the returned value for the "aName()" operation. This is the types name. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<LocalName-section,LocalName>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! interface 
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} aName   !<<CharacterString-section,CharacterString>> [1..1]  !The stored value "aName" is the returned value for the "aName()" operation.  
!===
|===   

=== Primitive types
The following classes are defined in <<ISO19103,(ISO 19103:2015)>>

==== Date and Time

[[Date-section]]
.Date Class
[cols="1a"]
|===
|*Date* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: !  
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! interface 
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} century   !<<CharacterString-section,CharacterString>> [1..1] !
 
!{set:cellbgcolor:#FFFFFF} day   !<<CharacterString-section,CharacterString>> [1..1]  !
 
!{set:cellbgcolor:#FFFFFF} month   !<<CharacterString-section,CharacterString>> [1..1] !
 
!{set:cellbgcolor:#FFFFFF} year   !<<CharacterString-section,CharacterString>>  [1..1] !
!===
|=== 

[[DateTime-section]]
.DateTime Class
[cols="1a"]
|===
|*DateTime* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: !  
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<Date-section,Date>> and <<Time-section,Time>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! interface 
!===
|=== 

[[Time-section]]
.Time Class
[cols="1a"]
|===
|*Time* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: !  
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! interface 
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} hour   !<<CharacterString-section,CharacterString>>  [1..1] !
 
!{set:cellbgcolor:#FFFFFF} minute   !<<CharacterString-section,CharacterString>>  [1..1] !
 
!{set:cellbgcolor:#FFFFFF} second   !<<CharacterString-section,CharacterString>>  [1..1] !
 
!{set:cellbgcolor:#FFFFFF} timeZone   !<<CharacterString-section,CharacterString>>  [1..1] !
!===
|===   

