[[conformance-section]]
== Conformance

This Standard defines a <<conceptual-model-definition,Conceptual Model>> which is independent of any encoding or formatting techniques. 
The <<standardization-target-definition,Standardization Target>> for this Standard is technology-specific POI <<implementation-specification-definition,Implementation Specifications>>.

=== OGC Implementation Specifications

Implementation Specifications define how a Conceptual Model should be implemented using a specific technology. Conformant Implementation Specifications provide evidence that they are an accurate representation of the Conceptual Model. This evidence should include implementations of the abstract tests specified in <<abstract-test-suite-section,Annex A>> (normative) of this document. 

Since this Standard is implementing technology agnostic, the specific techniques to be used for conformance testing cannot be specified. Implementation Specifications need to provide evidence of conformance which is appropriate for the implementing technologies. This evidence should be provided as Annex A to the Implementation Specification document.

=== Implementations

POI implementations will typically be a simplified representation of a more complex dataset. Implementors may want to extend the POI model to include properties specific to that dataset. These extensions are accomplished using the POI Payload mechanism described in <<poi_payload-section,POI Payload>>. Since the POI Payload has its own definition of syntax and semantics, conformance with the POI Standard cannot ensure payload conformance. 

=== Conformance Classes

This Standard identifies one "Core" <<conformance-class-definition,conformance class>>. This conformance class defines the conformance criteria for the requirements defined in one "Core" <<requirements-class-definition,requirements class>>. The tests this conformance class are documented in <<abstract-test-suite-section,Annex A>>. These tests are organized by Requirements Class. So an implementation of the Core conformance class must pass all tests specified in <<abstract-test-suite-section,Annex A>> for the Core Requirements Class.

The POI Conceptual Model is defined by the POI UML model. This Standard is a representation of that UML model in document form. In the case of a discrepancy between the UML model and this document, the UML model takes precedence.

=== Primitive Data Types

The Primitive Data Types (CharacterString, Integer, DateTime, etc.) are defined in ISO 19103. These Data Types are universal concepts. Therefore, no explicit conformance testing for these concepts is needed. Testing for conformance with the technology-specific implementation of these concepts should be documented in the corresponding Implementation Specification.  

