[[data_dictionary_section]]
=== POI Data Dictionary

The POI UML model is the normative definition of the POI Conceptual Model. The Data Dictionary tables in this section were software generated from the UML model. As such, this section provides a normative representation of the POI Conceptual Model.

[[AbstractFeature-section]]
[cols="1a"]
|===
|*AbstractFeature* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractFeature is the abstract superclass of all feature types within the POI Model. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! AnyFeature 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «FeatureType»
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} description «property»  !CharacterString  [0..*] !Provides further information on the feature.
 
!{set:cellbgcolor:#FFFFFF} featureID «property»  !GenericName [1..1]!Specifies the unique identifier of the feature that is valid in the instance document within which it occurs.
 
!{set:cellbgcolor:#FFFFFF} identifer «property»  !ScopedName [0..*] !Specifies the unique identifier of the feature that is valid globally.
 
!{set:cellbgcolor:#FFFFFF} name «property» !GenericName [0..*] !Specifies the name of the feature.
!===
|=== 

[[AbstractFeatureWithLifespan-section]]
[cols="1a"]
|===
|*AbstractFeatureWithLifespan* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractFeatureWithLifespan is the base class for all POI features. This class allows the optional specification of the real-world and database times for the existence of each feature. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! <<AbstractFeature-section,AbstractFeature>> 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} creationDate «property»  !DateTime [0..1] !Indicates the date at which a POI feature was added to the containing model.
 
!{set:cellbgcolor:#FFFFFF} terminationDate «property»  !DateTime [0..1] !Indicates the date at which a POI feature was removed from the containing model.
 
!{set:cellbgcolor:#FFFFFF} validFrom «property»  !DateTime [0..1] !Indicates the date at which a POI feature started to exist in the real world.
 
!{set:cellbgcolor:#FFFFFF} validTo «property»  !DateTime [0..1] !Indicates the date at which a POI feature ceased to exist in the real world.
!===
|=== 

[[AbstractPOI-section]]
[cols="1a"]
|===
|*AbstractPOI* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Point of Interest (POI) is a Feature which provides a concise summary of one or more associated Features. Its purpose is to provide easy access to key information about one or more real-world objects without the need to access or understand the underlying Feature data set. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! <<AbstractFeatureWithLifespan-section,AbstractFeatureWithLifespan>> 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF} hasPayload «property» !  <<POI_Payload-section,POI_Payload>>  
[0..*] !Indicates a payload associated with this POI.


!{set:cellbgcolor:#FFFFFF} hasFeatureOfInterest «property» !  <<FeatureOfInterest-section,FeatureOfInterest>>  
[0..*] !One or more Features which are represented by this POI. 

!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition* 
!{set:cellbgcolor:#FFFFFF} contactInfo «property»  !CI_Responsibility  [1..*] !Contact information for the creators and maintainers of this POI.
!{set:cellbgcolor:#FFFFFF} hasMetadata «property»  !<<Link-section,Link>>  [0..*] !An association with zero or more metadata records providing additional information about this POI and/or the associated Features of Interest.
!{set:cellbgcolor:#FFFFFF} keywords «property»  !MD_Keywords  [0..*] !Keywords used to aid in discovery of POIs of interest.
!{set:cellbgcolor:#FFFFFF} rights «property»  !MD_Constraints  [0..2] !Legal and security constraints applicable to this POI. 
!{set:cellbgcolor:#FFFFFF} symbology «property»  !<<Link-section,Link>>  [0..1] !A reference to information about rendering this POI. 
!===
|=== 

[[FeatureOfInterest-section]]
[cols="1a"]
|===
|*FeatureOfInterest* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! The thing whose property is being estimated or calculated during an Observation to arrive at a Result, or whose property is being manipulated by an Actuator, or which is being sampled or transformed in an act of Sampling. (SOSA) 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! AnyFeature 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «FeatureType»
!===
|=== 

[[PayloadDefinition-section]]
[cols="1a"]
|===
|*PayloadDefinition* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! The semantic model (ontology) for a POI payload.  
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! none 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «DataType»
!===
|=== 

[[PayloadSchema-section]]
[cols="1a"]
|===
|*PayloadSchema* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A model of the syntax of the POI payload. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! none 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «DataType»
!===
|=== 

[[POI-section]]
[cols="1a"]
|===
|*POI* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! An instance of a POI. Implements the AbstractPOI class. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! none 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} implements  !  <<AbstractPOI-section,AbstractPOI>>  
[1..1] !Identifies the abstract POI implemented by this POI
!===
|=== 

[[POI_Payload-section]]
[cols="1a"]
|===
|*POI_Payload* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A representation of properties of the FoI which are to be included in the POI. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! none 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «DataType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} hasDefinition «property» !  <<PayloadDefinition-section,PayloadDefinition>>  
[0..1] !A reference to the semantic model of this POI payload. 
!{set:cellbgcolor:#FFFFFF} hasFeatureOfInterest «property» !  <<FeatureOfInterest-section,FeatureOfInterest>>  
[0..*] !Indicates the Feature of Interest which is being summarized in this payload.
!{set:cellbgcolor:#FFFFFF} usesSchema «property» !  <<PayloadSchema-section,PayloadSchema>>  
[1..*] !A reference to the schema for this POI payload. 
!===
|===   





