.Preface

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.
////

[abstract]
== Abstract
The OGC Points of Interest (POI) Conceptual Model is an open data model for representing information about POI. 
The model is defined using a Unified Modeling Language (UML) object model. 
This UML model extends the ISO Technical Committee 211 (TC211) conceptual model standards for spatial and temporal data. 
Building on the ISO foundation assures that the features described in the POI Model share the same spatiotemporal universe as described by related standards (e.g. <<citygml,CityGML>>).

The goal for developing the OGC POI Conceptual Model is to reach a common definition of the basic entities, attributes, and relations of “points of interest.” 
In the broadest terms, a POI is a location about which information of general interest is available. 
"A POI can be as simple as a set of coordinates and an identifier, or more complex such as a three-dimensional model of a building with names in various languages, information about open and closed hours, and a civic address."^<<w3cpoi,W3C>>^

[security-considerations-section]
== Security Considerations

The POI Conceptual Model defines a POI as a type of Feature. 
By building on the same Feature Model as other OGC Feature models, POI implementations inherit the security controls and vulnerabilities of their associated Feature Dataset.
They are a Feature like any other. +

This document defines a Conceptual Model Standard. 
Implementations of this Standard (Implementation Standards) are free to add additional details and content necessary to enable implementation-specific security controls. 
In the event that anything in this Standard prevents implementation of needed controls, implementors are requested to notify the POI Standards Working Group (SWG) and help devise a solution.


