[[data_dictionary_section]]
=== POI Data Dictionary

The POI UML model is the normative definition of the POI Conceptual Model. The Data Dictionary tables in this section were software generated from the UML model. As such, this section provides a normative representation of the POI Conceptual Model.

[[AbstractFeature-section]]
[cols="1a"]
|===
|*AbstractFeature* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractFeature is the abstract superclass of all feature types within the PoI Model. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! <<AnyFeature-section,AnyFeature>> 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} description «property»  !<<CharacterString-section,CharacterString>>  [0..1] !Provides further information on the feature.
 
!{set:cellbgcolor:#FFFFFF} featureID «property»  !<<ID-section,ID>>  !Specifies the unique identifier of the feature that is valid in the instance document within which it occurs.
 
!{set:cellbgcolor:#FFFFFF} identifer «property»  !<<ScopedName-section,ScopedName>>  [0..1] !Specifies the unique identifier of the feature that is valid globally.
 
!{set:cellbgcolor:#FFFFFF} name «property»  !<<GenericName-section,GenericName>>  [0..*] !Specifies the name of the feature.
!===
|=== 

[[AbstractFeatureWithLifespan-section]]
[cols="1a"]
|===
|*AbstractFeatureWithLifespan* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractFeatureWithLifespan is the base class for all PoI features. This class allows the optional specification of the real-world and database times for the existence of each feature. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! <<AbstractFeature-section,AbstractFeature>> 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} creationDate «property»  !<<DateTime-section,DateTime>>  [0..1] !Indicates the date at which a POI feature was added to the containing model.
 
!{set:cellbgcolor:#FFFFFF} terminationDate «property»  !<<DateTime-section,DateTime>>  [0..1] !Indicates the date at which a POI feature was removed from the containing model.
 
!{set:cellbgcolor:#FFFFFF} validFrom «property»  !<<DateTime-section,DateTime>>  [0..1] !Indicates the date at which a POI feature started to exist in the real world.
 
!{set:cellbgcolor:#FFFFFF} validTo «property»  !<<DateTime-section,DateTime>>  [0..1] !Indicates the date at which a POI feature ceased to exist in the real world.
!===
|=== 

[[AbstractPOI-section]]
[cols="1a"]
|===
|*AbstractPOI* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Point of Interest (POI) is a Feature which provides a concise summary of one or more associated Features. Its purpose is to provide easy access to key information about one or more real-world objects without the need to access or understand the underlying Feature data set. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! <<AbstractFeatureWithLifespan-section,AbstractFeatureWithLifespan>> 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} hasFeatureOfInterest  !  <<FeatureOfInterest-section,FeatureOfInterest>>  
[0..*] !One or more Features which are represented by this POI. 
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} contactInfo «property»  !<<CI_Responsibility-section,CI_Responsibility>>  [1..*] !Contact information for the creators and maintainers of this POI.
 
!{set:cellbgcolor:#FFFFFF} hasFeatureOfInterest «property»  !<<Link-section,Link>>  [0..*] !One or more Features which are represented by this POI.
 
!{set:cellbgcolor:#FFFFFF} hasMetadata «property»  !<<Link-section,Link>>  [0..*] !An association with zero or more metadata records providing additional information about this POI and/or the associated Features of Interest.
 
!{set:cellbgcolor:#FFFFFF} keywords «property»  !<<MD_Keywords-section,MD_Keywords>>  [0..*] !Keywords used to aid in discovery of POIs of interest.
 
!{set:cellbgcolor:#FFFFFF} rights «property»  !<<MD_Constraints-section,MD_Constraints>>  [0..2] !Legal and security constraints applicable to this POI.
 
!{set:cellbgcolor:#FFFFFF} symbology «property»  !<<Link-section,Link>>  [0..1] !A reference to information about rendering this POI. 
!===
|=== 

[[FeatureOfInterest-section]]
[cols="1a"]
|===
|*FeatureOfInterest* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! The thing whose property is being estimated or calculated in the course of an Observation to arrive at a Result, or whose property is being manipulated by an Actuator, or which is being sampled or transformed in an act of Sampling. (SOSA) 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! <<AnyFeature-section,AnyFeature>> 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «FeatureType»
!===
|=== 

[[PayloadDefinition-section]]
[cols="1a"]
|===
|*PayloadDefinition* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! The semantic model (ontology) for a POI payload.  
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «DataType»
!===
|=== 

[[PayloadSchema-section]]
[cols="1a"]
|===
|*PayloadSchema* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A model of the syntax of the POI payload. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «DataType»
!===
|=== 

[[POI-section]]
[cols="1a"]
|===
|*POI* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! An instance of a POI. Implements the AbstractPOI class. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «FeatureType»
!===
|=== 

[[POI_Payload-section]]
[cols="1a"]
|===
|*POI_Payload* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A representation of properties of the FoI which are to be included in the POI. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «DataType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} usedBy  !  <<AbstractPOI-section,AbstractPOI>>  
[] !
!{set:cellbgcolor:#FFFFFF} hasDefinition  !  <<PayloadDefinition-section,PayloadDefinition>>  
[0..1] !
!{set:cellbgcolor:#FFFFFF} usesSchema  !  <<PayloadSchema-section,PayloadSchema>>  
[1..*] !
!{set:cellbgcolor:#FFFFFF} FoI  !  <<FeatureOfInterest-section,FeatureOfInterest>>  
[1..1] !
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} hasDefinition   !<<Link-section,Link>>  [1..0] !A reference to the semantic model of the payload for this POI. The target of this reference is an instance of the PayloadDefinition class.
 
!{set:cellbgcolor:#FFFFFF} usesSchema   !<<Link-section,Link>>  !A reference to the schema for the payload of this POI.  The target of this reference is an instance of the PayloadSchema class.
!===
|=== 

[[ID-section]]
[cols="1a"]
|===
|*ID* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! ID is a basic type that represents a unique identifier. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «Type»
!===
|=== 

[[Integer-section]]
[cols="1a"]
|===
|*Integer* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: !  
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «Type»
!===
|=== 

[[Link-section]]
[cols="1a"]
|===
|*Link* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: !  
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «Type»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} href   !<<String-section,String>>  !Supplies the URI to a remote resource (or resource fragment).
 
!{set:cellbgcolor:#FFFFFF} hreflang   !<<String-section,String>>  [0..1] !A hint indicating what the language of the result of dereferencing the link should be.
 
!{set:cellbgcolor:#FFFFFF} length   !<<int-section,int>>  !
 
!{set:cellbgcolor:#FFFFFF} rel   !<<String-section,String>>  !The type or semantics of the relation.
 
!{set:cellbgcolor:#FFFFFF} title   !<<String-section,String>>  [0..1] !Used to label the destination of a link such that it can be used as a human-readable identifier.
 
!{set:cellbgcolor:#FFFFFF} type   !<<String-section,String>>  [0..1] !A hint indicating what the media type of the result of dereferencing the link should be.
!===
|=== 

[[String-section]]
[cols="1a"]
|===
|*String* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: !  
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: !  «Type»
!===
|===     
