[[conformance-section]]
== Conformance

This standard defines a <<conceptual-model-definition,Conceptual Model>> which is independent of any encoding or formatting techniques. The <<standardization-target-definition>> Standardization Targets for this standard are:

. <<conceptual-model-definition,Conceptual Models>> (extended versions of this conceptual model)
. <<implementation-specification-definition,Implementation Specifications>> (encodings of this conceptual model)

=== Conceptual Models

A Conceptual Model standardization target is a version of the POI Conceptual Model (CM) tailored for a specific user community. This tailoring can include:

. Reduction of the multiplicity for an attribute or association
. Restriction on the valid values for an attribute
. Additional [underline]#optional# POI properties

Of these options, actions #1 and #2 can be performed when creating an implementation specification. Only action #3 requires an extension of the POI conceptual model. 

=== Implementation Specifications

Implementation Specifications define how a Conceptual Model should be implemented using a specific technology. Conformant Implementation Specifications provide evidence that they are an accurate representation of the Conceptual Model. This evidence should include implementations of the abstract tests specified in Annex A (normative) of this document. 

Since this standard is agnostic to the implementing technologies, the specific techniques to be used for conformance testing cannot be specified. Implementation Specifications need to provide evidence of conformance which is appropriate for the implementing technologies. This evidence should be provided as an annex to the Implementation Specification document.

=== Implementations

POI implementations will typically be a simplified representation of a more complex dataset. Implementors may want to extend the POI model to include properties specific to that dataset. These extensions are accomplished using the POI Payload mechanism described in <<poi_payload-section,POI Payload>>. Since the POI Payload has its own definition of syntax and semantics, conformance with the POI Standard cannot ensure payload conformance. 

=== Conformance Classes

This standard identifies one "Core" <<conformance-class-definition,conformance class>>. This conformance class defines the conformance criteria for the requirements defined in one "Core" <<requirements-class-definition,requirements class>>. The tests this conformance class are documented in Annex A. These tests are organized by Requirements Class. So an implementation of the Core conformance class must pass all tests specified in Annex A for the Core Requirements Class.

The POI Conceptual Model is defined by the POI UML model. This standard is a representation of that UML model in document form. In the case of a discrepancy between the UML model and this document, the UML model takes precedence.