.Preface

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.
////

[abstract]
== Abstract
The OGC Points of Interest (POI) Conceptual Model is an open data model for representing information about POI. In the broadest terms, a POI is a location about which information of general interest is available. Such information may be of interest to people speaking multiple languages. Therefore, a POI often requires the use of internationalized text.

It is not necessary to develop new techniques for internationlized text. There are many existing approaches in both our foundational Standards and common use. This document seeks to capture these techniques in one place, facilitating their application to POIs and potentially OGC Standards in general.

[security-considerations-section]
== Security Considerations

This document deales with techniques to internationalize text. It should not have any security ramifications.
