== Terms and Definitions

[[application_schema-definition]]
=== application schema::

Add definition from 19109

[.source]
<<ISO19109,clause 4.27>>

[[class-definition]]
=== class::

description of a set of _objects_ that share the same _attributes_, _operations_, methods, relationships, and semantics

NOTE: A _class_ may use a set of interfaces to specify collections of _operations_ it provides to its environment.
The term was first used in this way in the general theory of object-oriented programming, and later adopted for use in this same sense in UML.

[.source]
<<ISO19103,clause 4.27>>, Note 1 to entry has been added from ISO 19117:2012, 4.2

[[concept-definition]]
=== concept::

unit of knowledge created by a unique combination of characteristics

NOTE: _Concepts_ (<<concept-definition>>) are not necessarily bound to particular languages. They are, however, influenced by the social or cultural background which often leads to different categorizations.

[.source]
<<ISO1087-1,clause 3.2.1>>

[[conceptual-model-definition]] 
=== conceptual model::

model that defines _concepts_ (<<concept-definition>>) of a universe of discourse

[.source]
<<ISO19101-1,clause 4.1.5>>

[[conformance-class-definition]]
=== conformance class::

a class of conformance tests. A conformant implementation must pass all the tests in the class.

[.source]
<<ogcdr,OGC Definitions Register>>

[[feature-definition]]
=== feature::

abstraction of real-world phenomena

NOTE: A _feature_ (<<feature-definition>>) may occur as a type or an instance. In this document, _feature_ (<<feature-definition>>) instance is meant unless otherwise specified.

[.source]
<<ISO19101-1,clause 4.1.11>>, Note 1 to entry has been added from ISO 19156, 4.6

[[feature-type-definition]]
=== feature type::

_class_ (<<class-definition>>) of _features_ (<<feature-definition>>) having common characteristics

[.source]
<<ISO19156,clause 4.7>>

[[implementation-specification-definition]]
=== implementation Standard::

guidance for software engineers that is so specific that any two independent software implementations of the Standard can "plug and play" for each other.

[.source]
<<ogcdr,OGC Definitions Register>>

[[requirements-class-definition]]
=== requirements class::

a class of requirements, comprising a logical grouping of normative statements that shall be satisfied as a group in conformant implementations. May have dependencies on other _requirements classes_ (<<requirements-class-definition>>) , but there should be no circular dependencies else the classes must always be satisfied together so are functionally one class.

[.source]
<<ogcdr,OGC Definitions Register>>

[[standardization-target-definition]]
=== standardization target::

entity to which some requirements of a standard apply

NOTE:: The standardization target is the entity which may receive a certificate of conformance for a requirements class.

[.source]
<<modspec,OGC 08-131r3>>

