== Terms and Definitions
This document uses the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this Standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

[[location]]
location::
particular _place_ or _position_

NOTE: A _location_ identifies a geographic _place_.

NOTE: _Locations_ are physically fixed points, typically on the surface of the Earth, although _locations_ can be relative to other, non-earth centric coordinate reference systems. 

NOTE: _Locations_ can be a single point, a centroid, a minimum bounding rectangle, or a set of vectors. 

NOTE: A _location_ should be persistent over time and does not change. 

NOTE: Multiple _POIs_ may share the same _location_. 

NOTE: When a _POI_ physically moves it is understood to have acquired a new _location_.

[.source]
<<ISO19112,clause 3.1.3>>

[[point]]
point::
0-dimensional geometric primitive, representing a _position_ 

[.source]
<<ISO19107>>
#ISO19107,clause xxxx - get definition clause#

[[point_of_interest]]
point of interest::
alt:[POI]

_location_ where one can find a _place_, product or service

NOTE: A _POI_ is typically identified by _name_ rather than by an _address_.

NOTE: A _POI_ is characterized by _type_, which may be used as a _reference point_ or a target in a _location_ based service request.

NOTE: A _POI_ does not exclude the labeling, identification, and tracking of persons and other physical objects that have no permanent location.

[example]
destination of a route; such as, Boston

[[position]]
position::
data type that describes a _point_ or _geometry_ potentially occupied by an object or person

[.source]
<<ISO19133>>
#ISO19133,clause xxxx - get definition clause#

[[application-schema]] application schema::

A set of conceptual schema for data required by one or more applications. An application schema contains selected parts of the base schemas presented in the ORM Information Viewpoint.

Designers of application schemas may extend or restrict the types defined in the base schemas to define appropriate types for an application domain. Application schemas are information models for a specific information community.

[.source]
OGC Definitions Register at http://www.opengis.net/def/glossary/term/ApplicationSchema

[[codelist]] codelist::

A value domain including a code for each permissible value.

[[conceptual-model]] conceptual model::

model that defines concepts of a universe of discourse

[.source]
<<ISO1901:2014>>
#ISO 19101-1:2014,clause 4.1.5 - get definition clause#

[[conceptual-schema]] conceptual schema::

. formal description of a conceptual model [ISO 19101-1:2014, 4.1.6]
. base schema. Formal description of the model of any geospatial information. Application schemas are built from conceptual schemas.

OGC Definitions Register at http://www.opengis.net/def/glossary/term/ConceptualSchema

Implementation Specification Specified on the OGC Document Types Register at http://www.opengis.net/def/doc-type/is

[[platform]] Platform (Model Driven Architecture)::

the set of resources on which a system is realized.

[.source]
<<mdaguide>>
#Object Management Group, Model Driven Architecture Guide rev. 2.0#

[[platform-independent-model]] Platform Independent Model:

a model that is independent of a specific platform

[.source]
<<mdaguide>>
#Object Management Group, Model Driven Architecture Guide rev. 2.0#

[[platform-specific-model]] Platform Specific Model:

a model of a system that is defined in terms of a specific platform

[.source]
<<mdaguide>>
#Object Management Group, Model Driven Architecture Guide rev. 2.0#
