[[military_use_case]]
=== Military Use Case

*Contributed By:* Joetta Kreck (AGC) – Joetta.l.kreck@usace.army.mil

*Motivation:*

Use POIs to simplify data collection and use.

*Summary*

POIs are a simplification of a Feature dataset. The selection and population of a POI is mission-specific. There is no standard attribution for a POI Feature. Rather, the POI Feature Type serves as a scafolding which is attributed based on the data available and the needs of the user.

<<use_case_details_military,Click to view>> full use case description

*Related Use Cases*

TBD

*Roles:*

<List all stakeholders that are involved in the use case. Stakeholders are described in the <<stakeholders-section,Stakeholders Section>> of this document. Each listed stakeholder should be hyperlinked to its description.>

*Devices:*

NA

*Data:*

A Feature dataset which is the source or target of the POI.

*Dependencies:*

NA

*Requirements:*

TBD

*Variants:*

None

*Security Considerations:*

TBD

*Privacy Considerations:*

TBD

*Comments:*
