== Terms and definitions

This document uses the terms defined in Sub-clause 5.3 of <<OGC06-121r9>>, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.
////
[[boundary]]
=== boundary

set that represents the limit of an entity

NOTE: _Boundary_ is most commonly used in the context of geometry, where the set is a collection of points or a collection of objects
that represent those points. In other domains, the term is used metaphorically to describe the transition between an entity and the rest of its domain of discourse.

[.source]
<<ISO19107,clause 4.6>>
////


[[coordinate]]
=== coordinate
sequence of n numbers designating the _position_ of a _point_ in n-dimensional space 

[.source]
<<ISO19111>>
#ISO19111,clause xxxx - get definition clause#


[[coordinate_set]]
=== coordinate set
individual parts of a coordinate

[example]
coordinate pair of latitude and longitude values.


[[coordinate_reference_system]]
=== coordinate reference system

_coordinate system_ that is related to an object by a _datum_ (<<datum>>)

NOTE: Geodetic and vertical datums are referred to as reference frames.

NOTE: For geodetic and vertical _datums_ (<<datum>>), the object will be the Earth.
In planetary applications, geodetic and vertical reference frames may be applied to other celestial bodies.

[.source]
<<ISO19111,clause 3.1.9>>


[[coordinate_system]]
=== coordinate system

set of mathematical rules for specifying how _coordinates_ are to be assigned to _points_

[.source]
<<ISO19111,clause 3.1.11>>


[[datum]]
=== datum
alt:[reference frame]

parameter or set of parameters that realize the _positions_ of the origin, the scale, and the orientation of a _coordinate system_ (<<coordinate_system>>)

[.source]
<<ISO19111,clause 3.1.15>>



[[geolocation]]
=== geolocation
identification of the real world geographic _location_ of an object



[[location]]
=== location

particular _place_ or _position_

NOTE: A _location_ identifies a geographic _place_.

NOTE: _Locations_ are physically fixed points, typically on the surface of the Earth, although _locations_ can be relative to other, non-earth centric coordinate reference systems. 

NOTE: _Locations_ can be a single point, a centroid, a minimum bounding rectangle, or a set of vectors. 

NOTE: A _location_ should be persistent over time and does not change. 

NOTE: Multiple _POIs_ may share the same _location_. 

NOTE: When a _POI_ physically moves it is understood to have acquired a new _location_.

[.source]
<<ISO19112,clause 3.1.3>>


[[place]]
=== place

semantic description of a _location_

NOTE: A _place_ is a human construct which typically has a coarse level of spatial granularity. 

NOTE: A _place_ is generally a larger scale administrative construct, either informally or formally defined. 

NOTE: A _place_ can be informally or colloquially defined, such as the Home Counties in the United Kingdom and the Bay Area in the United States.

NOTE: _Places_ have spatial relationships; with parents, children, adjacencies and contained by semantics.

NOTE: _Places_ have the same attribute set as _POIs_, although often with differing interpretations based on scale; for example, the address of a _Place_ or its URI might refer to the address of the administrative or governing body of the _place_. 

NOTE: A _place_ typically contains multiple _POIs_ and can also be coterminous with a _POI_. In the former case, a _place_, such as a city or a neighborhood, will contain multiple _POIs_. In the latter case, a _place_ and a _POI_ will occupy the same _position_ and extent, such as in the case of Yellowstone National Park, which is both a _Place_ and a _POI_.

[example]
Countries, states, counties, districts, neighborhoods and postal codes or telephone area codes are all places. 




[[point]]
=== point
0-dimensional geometric primitive, representing a _position_ 

[.source]
<<ISO19107>>
#ISO19107,clause xxxx - get definition clause#



[[point_of_interest]]
=== point of interest
alt:[POI]

_location_ where one can find a _place_, product or service

NOTE: A _POI_ is typically identified by _name_ rather than by an _address_.

NOTE: A _POI_ is characterized by _type_, which may be used as a _reference point_ or a target in a _location_ based service request.

NOTE: A _POI_ does not exclude the labeling, identification, and tracking of persons and other physical objects that have no permanent location.

[example]
destination of a route; such as, Boston



[[position]]
=== position
data type that describes a _point_ or _geometry_ potentially occupied by an object or person

[.source]
<<ISO19133>>
#ISO19133,clause xxxx - get definition clause#



[[route]]
=== route
sequence of _links_ and / or partial _links_ that describe a _path_, usually between two _positions_, within a _network_
////
[def from OGC API Routes spec ]
route
sequence of connected segments providing directions to travel between specific _waypoints_

NOTE: This definition doesn’t use the definition from ISO 19134:2007 because of use of terms such as "links" and "network".
////
[.source]
<<19134:2007>>
#19134:2007,clause xxxx - get definition clause#

