[[req_core_abstract-poi]]
.Requirement - Abstract POI
[requirement]
====
[%metadata]
identifier:: /req/core/abstract-poi

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL be an accurate representation of the UML model for that class.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_feature_with_lifespan,/req/core/poi-feature-with-lifespan>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_poi_contactinfo,/req/core/poi-contactinfo>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_poi_featureofinterest,/req/core/poi-featureofinterest>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_poi_metadata,/req/core/poi-metadata>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_poi_keywords,/req/core/poi-keywords>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_poi_rights,/req/core/poi-rights>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_poi_symbology,/req/core/poi-symbology>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_poi-haspayload,/req/core/poi-haspayload>>.
--

====

[[req_core_poi_contactInfo]]
.Requirement - POI Contact Information
[requirement]
====
[%metadata]
identifier:: /req/core/poi-contactInfo
[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI class SHALL include one or more `contactInfo` attributes.
--

[.component,class=part]
--
Encodings of the `contactInfo` attribute SHALL be a valid implementation of the CI_Responsibility class from <<ISO19115,ISO 19115-1:2014>>
--
====

[[req_core_poi_featureofinterest]]
.Requirement - POI Feature of Interest
[requirement]
====
[%metadata]
identifier:: /req/core/poi-featureofinterest
[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero or more associated instances of the `FeatureOfInterest` class.
--

[.component,class=part]
--
The target of the `hasFeatureOfInterest` aggregation SHALL be a valid implementation of the Feature class from <<ISO19109,ISO 19109:2015>>
--
====

[[req_core_poi_metadata]]
.Requirement - POI Metadata
[requirement]
====
[%metadata]
identifier:: /req/core/poi-metadata
[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero or more `metadata` attributes.
--

[.component,class=part]
--
An implementation of the `metadata` association SHALL comply with requirement <<req_core_Link,/req/core/link>>.
--
====

[[req_core_poi_keywords]]
.Requirement - POI Keywords
[requirement]
====
[%metadata]
identifier:: /req/core/poi-keywords
[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero or more `keywords` attributes.
--

[.component,class=part]
--
Encodings of the `keywords` attribute SHALL be a valid implementation of the MD_Keywords class from <<ISO19115,ISO 19115-1:2014>>.
--
====

[[req_core_poi_rights]]
.Requirement - POI Rights
[requirement]
====
[%metadata]
identifier:: /req/core/poi-rights
[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero, one, or two `rights` attributes.
--

[.component,class=part]
--
Encodings of the `rights` attribute SHALL be a valid implementation of the MD_Constraints class from <<ISO19115,ISO 19115-1:2014>>.
--
====

[[req_core_poi_symbology]]
.Requirement - POI Symbology
[requirement]
====
[%metadata]
identifier:: /req/core/poi-symbology
[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero or one `symbology` attributes.
--

[.component,class=part]
--
Encodings of a `symbology` attribute SHALL comply with requirement <<req_core_Link,/req/core/link>>.
--
====

[[req_core_poi-haspayload]]
.Requirement - POI Has Payload
[requirement]
====
[%metadata]
identifier:: /req/core/poi-haspayload
[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero or more associated instances of the `POI_Payload` class.
--

[.component,class=part]
--
The associated `POI_Payload` classes SHALL comply with requirement <<req_core_poi-payload,/req/core/poi-payload>>.
--
====

[[req_core_Link]]
.Requirement - Link Class
[requirement]
====
[%metadata]
identifier:: /req/core/link
[.component,class=part]
--
The encoding of the Link class SHALL be implemented using a hyperlink approach appropriate for implementing technology.
--
====
