[[req_core_abstract-poi]]
.Requirement - Abstract POI
[requirement]
====
[%metadata]
label:: /req/core/req-abstract-poi
[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_feature_with_lifespan,/req/core/req-poi-feature-with-lifespan>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_POI_contactInfo,/req/core/req-poi-contactInfo>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_POI_featureOfInterest,/req/core/req-poi-featureOfInterest>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_POI_metadata,/req/core/req-poi-metadata>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_POI_keywords,/req/core/req-poi-keywords>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_POI_rights,/req/core/req-poi-rights>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_POI_symbology,/req/core/req-poi-symbology>>.
--

[.component,class=part]
--
An instantiation of the Abstract POI class SHALL comply with requirement <<req_core_POI_Payload,/req/core/req-poi-payload>>.
--

====

[[req_core_POI_contactInfo]]
.Requirement - POI Contact Information
[requirement]
====
[%metadata]
label:: /req/core/req-poi-contactInfo
[.component,class=part]
--
An encoding of the Abstract POI class SHALL include one or more `contactInfo` attributes.
--

[.component,class=part]
--
Encodings of the `contactInfo` attribute SHALL be a valid implementation of the CI_Responsibility class from ISO 19115-1:2014
--
====

[[req_core_POI_featureOfInterest]]
.Requirement - POI Feature of Interest
[requirement]
====
[%metadata]
label:: /req/core/req-poi-featureOfInterest
[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero or more associated instances of the `FeatureOfInterest` class.
--
====

[[req_core_POI_metadata]]
.Requirement - POI Metadata
[requirement]
====
[%metadata]
label:: /req/core/req-poi-metadata
[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero or more `metadata` attributes.
--

[.component,class=part]
--
Encodings of the `metadata` attribute SHALL be a resolvable reference to a Metadata resource.
--
[.component,class=part]
--
Encodings of a `metadata` attribute SHALL comply with requirement <<req_core_Link,/req/core/req-link>>.
--
====

[[req_core_POI_Payload]]
.Requirement - POI Payload
[requirement]
====
[%metadata]
label:: /req/core/req-poi-payload
[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero or more associated instances of the `POI_Payload` class.
--

[.component,class=part]
--
An encoding of the Abstract POI class SHALL comply with requirement <<req_core_POI-Payload_class,/req/core/req-poi-payload-class>>.
--
====

[[req_core_POI_keywords]]
.Requirement - POI Keywords
[requirement]
====
[%metadata]
label:: /req/core/req-poi-keywords
[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero or more `keyword` attributes.
--

[.component,class=part]
--
Encodings of the `keyword` attribute SHALL be a valid implementation of the MD_Keyword class from ISO 19115-1:2014
--
====

[[req_core_POI_rights]]
.Requirement - POI Rights
[requirement]
====
[%metadata]
label:: /req/core/req-poi-rights
[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero, one, or two `rights` attributes.
--

[.component,class=part]
--
Encodings of the `rights` attribute SHALL be a valid implementation of the MD_Constraints class from ISO 19115-1:2014
--
====

[[req_core_POI_symbology]]
.Requirement - POI Symbology
[requirement]
====
[%metadata]
label:: /req/core/req-poi-symbology
[.component,class=part]
--
An encoding of the Abstract POI class SHALL include zero or one `symbology` attributes.
--

[.component,class=part]
--
Encodings of the `symbology` attribute SHALL be a resolvable reference to a symbology resource.
--
[.component,class=part]
--
Encodings of a `symbology` attribute SHALL comply with requirement <<req_core_Link,/req/core/req-link>>.
--
====

[[req_core_Link]]
.Requirement - Link Class
[requirement]
====
[%metadata]
label:: /req/core/req-link
[.component,class=part]
--
TBD.
--
====
