[[req_core_abstract_feature]]
.Requirement - Abstract Feature
[requirement]
====
[%metadata]
label:: /req/core/req-abstractfeature
[.component,class=part]
--
An encoding of the AbstractFeature class SHALL be a compliant extension of the AnyFeature class defined in <<ISO19109,ISO 19109>>.
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL comply with requirement <<req_core_abstractfeature-description,/req/core/req-abstractfeature-description>>.
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL comply with requirement <<req_core_abstractfeature-featureID,/req/core/req-abstractfeature-featureid>>.
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL comply with requirement <<req_core_abstractfeature-identifier,/req/core/req-abstractfeature-identifier>>.
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL comply with requirement <<req_core_abstractfeature-name,/req/core/req-abstractfeature-name>>.
--
====

[[req_core_abstractfeature-description]]
.Requirement - Abstract Feature Description
[requirement]
====
[%metadata]
label:: /req/core/req-abstractfeature-description
[.component,class=part]
--
An encoding of the AbstractFeature class SHALL include zero or one `description` attributes.
--

[.component,class=part]
--
Encodings of the `description` attribute SHALL be a valid implementation of the CharacterString class from ISO 19103.
--
====

[[req_core_abstractfeature-featureid]]
.Requirement - Abstract Feature Feature Id
[requirement]
====
[%metadata]
label:: /req/core/req-abstractfeature-featureid
[.component,class=part]
--
An encoding of the AbstractFeature class SHALL include one `featureID` attributes.
--

[.component,class=part]
--
Encodings of the `featureID` attribute SHALL be a valid implementation of the ID class from ISO 19103.
--
====

[[req_core_abstractfeature-identifier]]
.Requirement - Abstract Feature Identifier
[requirement]
====
[%metadata]
label:: /req/core/req-abstractfeature-identifier
[.component,class=part]
--
An encoding of the AbstractFeature class SHALL include zero or one `identifier` attributes.
--

[.component,class=part]
--
Encodings of the `identifier` attribute SHALL be a valid implementation of the ScopedName class from ISO 19103.
--
====

[[req_core_abstractfeature-name]]
.Requirement - Abstract Feature Name
[requirement]
====
[%metadata]
label:: /req/core/req-abstractfeature-name
[.component,class=part]
--
An encoding of the AbstractFeature class SHALL include zero or more `name` attributes.
--

[.component,class=part]
--
Encodings of the `name` attribute SHALL be a valid implementation of the GenericName class from ISO 19103.
--
====
