[[req_core_feature_with_lifespan]]
.Requirement - Feature with Lifespan
[requirement]
====
[%metadata]
label:: /req/core/featurewithlifespan
[.component,class=part]
--
An instantiation of the AbstractFeatureWithLifespan class SHALL be an accurate representation of the UML model for that class.
--

[.component,class=part]
--
An encoding of the AbstractFeatureWithLifespan class SHALL comply with requirement <<req_core_abstractfeature,/req/core/abstractfeature>>.
--

[.component,class=part]
--
An encoding of the AbstractFeatureWithLifespan class SHALL comply with requirement <<req_core_feature_with_lifespan_creationdate,/req/core/featurewithlifespan-creationdate>>.
--

[.component,class=part]
--
An encoding of the AbstractFeatureWithLifespan class SHALL comply with requirement <<req_core_feature_with_lifespan_terminationdate,/req/core/featurewithlifespan-terminationdate>>.
--

[.component,class=part]
--
An encoding of the AbstractFeatureWithLifespan class SHALL comply with requirement <<req_core_feature_with_lifespan_validfrom,/req/core/featurewithlifespan-validfrom>>.
--

[.component,class=part]
--
An encoding of the AbstractFeatureWithLifespan class SHALL comply with requirement <<req_core_feature_with_lifespan_validto,/req/core/featurewithlifespan-validto>>.
--

====

[[req_core_feature_with_lifespan_creationdate]]
.Requirement - Feature with Lifespan Creation Date
[requirement]
====
[%metadata]
label:: /req/core/featurewithlifespan-creationdate
[.component,class=part]
--
An instantiation of the AbstractFeatureWithLifespan class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the AbstractFeatureWithLifespan class SHALL include zero or one `creationDate` attributes.
--

[.component,class=part]
--
Encodings of the `creationDate` attribute SHALL be a valid implementation of the DateTime class from ISO 19103.
--
====

[[req_core_feature_with_lifespan_terminationdate]]
.Requirement - Feature with Lifespan Termination Date
[requirement]
====
[%metadata]
label:: /req/core/featurewithlifespan-terminationdate
[.component,class=part]
--
An instantiation of the AbstractFeatureWithLifespan class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the AbstractFeatureWithLifespan class SHALL include zero or one `terminationDate` attributes.
--

[.component,class=part]
--
Encodings of the `terminationDate` attribute SHALL be a valid implementation of the DateTime class from ISO 19103.
--
====

[[req_core_feature_with_lifespan_validfrom]]
.Requirement - Feature with Lifespan Valid From
[requirement]
====
[%metadata]
label:: /req/core/featurewithlifespan-validfrom
[.component,class=part]
--
An instantiation of the AbstractFeatureWithLifespan class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the AbstractFeatureWithLifespan class SHALL include zero or one `validFrom` attributes.
--

[.component,class=part]
--
Encodings of the `validFrom` attribute SHALL be a valid implementation of the DateTime class from ISO 19103.
--
====

[[req_core_feature_with_lifespan_validto]]
.Requirement - Feature with Lifespan Valid To
[requirement]
====
[%metadata]
label:: /req/core/featurewithlifespan-validto
[.component,class=part]
--
An instantiation of the AbstractFeatureWithLifespan class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the AbstractFeatureWithLifespan class SHALL include zero or one `validTo` attributes.
--

[.component,class=part]
--
Encodings of the `validTo` attribute SHALL be a valid implementation of the DateTime class from ISO 19103.
--
====

