[[req_core_poi_payload]]
.Requirement - POI-Payload
[requirement]
====
[%metadata]
identifier:: /req/core/poi_payload

[.component,class=part]
--
An instantiation of the POI_Payload class SHALL be an accurate representation of the UML model for that class.
--

[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with requirement <<req_core_poi_payload-hasfeatureofinterest,/req/core/poi_payload-hasfeatureofinterest>>.
--

[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with requirement <<req_core_poi_payload-hasdefinition,/req/core/poi_payload-hasdefinition>>.
--

[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with requirement <<req_core_poi_payload-usesschema,/req/core/poi_payload-usesschema>>.
--
====

[[req_core_poi_payload-hasfeatureofinterest]]
.Requirement - POI Payload Has Feature of Interest
[requirement]
====
[%metadata]
identifier:: /req/core/poi_payload-hasfeatureofinterest
[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI_Payload class SHALL include zero or more `hasFeatureOfInterest` aggregations.
--

[.component,class=part]
--
The target of a `hasFeatureOfInterest` aggregation SHALL be a valid implementation of the Feature class from <<iso19109,ISO 19109:2015>>
--
====

[[req_core_poi_payload-hasdefinition]]
.Requirement - POI Payload has definition
[requirement]
====
[%metadata]
identifier:: /req/core/poi_payload-hasdefinition
[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI_Payload class SHALL include no more than one `hasDefinition` aggregations.
--

[.component,class=part]
--
The target of a `hasDefinition` aggregation SHALL be a valid ontology for the implementing technology
--
====

[[req_core_poi_payload-usesschema]]
.Requirement - POI Payload Uses Schema
[requirement]
====
[%metadata]
identifier:: /req/core/poi_payload-usesschema
[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI_Payload class SHALL include one or more `usesSchema` aggregations.
--

[.component,class=part]
--
The target of a `usesSchema` aggregation SHALL be a valid schema for the implementing technology.
--
====

