[[req_core_abstractfeature]]
.Requirement - Abstract Feature
[requirement]
====
[%metadata]
identifier:: /req/core/abstractfeature
[.component,class=part]
--
An instantiation of the AbstractFeature class SHALL be an accurate representation of the UML model for that class.
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL be a compliant extension of the AnyFeature class defined in <<ISO19109,ISO 19109>>.
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL comply with requirement <<req_core_abstractfeature-description,/req/core/abstractfeature-description>>.
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL comply with requirement <<req_core_abstractfeature-featureid,/req/core/abstractfeature-featureid>>.
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL comply with requirement <<req_core_abstractfeature-identifier,/req/core/abstractfeature-identifier>>.
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL comply with requirement <<req_core_abstractfeature-name,/req/core/abstractfeature-name>>.
--
====

[[req_core_abstractfeature-description]]
.Requirement - Abstract Feature Description
[requirement]
====
[%metadata]
identifier:: /req/core/abstractfeature-description
[.component,class=part]
--
An instantiation of the AbstractFeature class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL include zero or one `description` attributes.
--
====

[[req_core_abstractfeature-featureid]]
.Requirement - Abstract Feature Feature Id
[requirement]
====
[%metadata]
identifier:: /req/core/abstractfeature-featureid
[.component,class=part]
--
An instantiation of the AbstractFeature class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL include one `featureID` attributes.
--
====

[[req_core_abstractfeature-identifier]]
.Requirement - Abstract Feature Identifier
[requirement]
====
[%metadata]
identifier:: /req/core/abstractfeature-identifier
[.component,class=part]
--
An instantiation of the AbstractFeature class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL include zero or one `identifier` attributes.
--
====

[[req_core_abstractfeature-name]]
.Requirement - Abstract Feature Name
[requirement]
====
[%metadata]
identifier:: /req/core/abstractfeature-name
[.component,class=part]
--
An instantiation of the AbstractFeature class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the AbstractFeature class SHALL include zero or more `name` attributes.
--
====
