[[req_core_POI-Payload-2]]
.Requirement - POI-Payload-2
[requirement]
====
[%metadata]
identifier:: /req/core/poi-payload-2

[.component,class=part]
--
An instantiation of the POI_Payload class SHALL be an accurate representation of the UML model for that class.
--

[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with requirement <<req_core_poi-payload_featureofinterest,/req/core/poi_payload/featureofinterest>>.
--

[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with requirement <<req_core_poi-payload_hasdefinition,/req/core/poi_payload/hasDefinition>>.
--

[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with requirement <<req_core_poi-payload_usesschema,/req/core/poi_payload/usesSchema>>.
--
====

[[req_core_poi-payload_featureofinterest]]
.Requirement - POI Payload Feature of Interest
[requirement]
====
[%metadata]
identifier:: /req/core/poi_payload/featureofinterest
[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI_Payload class SHALL include zero or more `hasFeatureOfInterest` aggregations.
--

[.component,class=part]
--
The target of a `hasFeatureOfIntestest` aggregation SHALL be a valid implementation of the Feature class from <<iso19109,ISO 19109:2015>>
--
====

[[req_core_poi-payload_hasdefinition]]
.Requirement - POI Payload has definition
[requirement]
====
[%metadata]
identifier:: /req/core/poi_payload/hasDefinition
[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI_Payload class SHALL include no more than one `hasDefinition` aggregations.
--

[.component,class=part]
--
The target of a `hasDefinition` aggregation SHALL be a valid ontology for the implementing technology
--
====

[[req_core_poi-payload_usesschema]]
.Requirement - POI Payload Uses Schema
[requirement]
====
[%metadata]
identifier:: /req/core/poi_payload/usesSchema
[.component,class=part]
--
An instantiation of the POI_Payload class SHALL comply with the following criteria:
--

[.component,class=part]
--
An encoding of the Abstract POI_Payload class SHALL include one or more `usesSchema` aggregations.
--

[.component,class=part]
--
The target of a `usesSchema` aggregation SHALL be a valid schema for the implementing technology.
--
====

