.Preface

*OGC Declaration*

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium Inc. shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.

[abstract]
== Abstract

A Point of Interest (POI) .....

This standard defines the resources listed in <<tldnr>>. For an overview of the resources, see section <<core-overview,7.1 Overview>>.

[#tldnr,reftext='{table-caption} {counter:table-num}']
.Overview of resources, applicable HTTP methods and links to the document sections
[cols="32,25,10,33",options="header"]
!===
|Resource |Path |HTTP method |Document reference
|Landing page |`/` |GET |<<_api_landing_page,7.2 API landing page>>
|API definition |`/api` |GET |<<_api_definition_2,7.3 API definition>>
|Conformance classes |`/conformance` |GET |<<_declaration_of_conformance_classes,7.4 Declaration of conformance classes>>
|Feature collections metadata |`/collections` |GET |<<_feature_collections_metadata,7.11 Feature collections metadata>>
|Feature collection metadata |`/collections/{name}` |GET |<<_feature_collection_metadata, 7.12 Feature collection metadata>>
|Feature collection |`/collections/{name}/items` |GET |<<_feature_collections,7.13 Feature collections>>
|Feature |`/collections/{name}/items/{fid}` |GET |<<_feature_2,7.14 Feature>>
!===

== Submitters

All questions regarding this submission should be directed to the editors or the submitters:

|===
|*Name* |*Affiliation*

|Name |Organization
|Name _(editor)_ |Organization
|Name |Organization
|Name _(editor)_ |Organization
|===

== Contributors

The following OGC members are contributors to the POI specification:

|===
|*Name* |*Affiliation*

|Name |Organization
|Name |Organization
|Name |Organization
|Name |Organization
|===
