== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of <<OGC06-121r8>>, which is based on <<ISOIECDIR2>>. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

CAUTION: Add link to the informative POI Guide, once it is available.

=== dataset
collection of data, published or curated by a single agent, and available for access or download in one or more formats 

[.source]
<<DCAT>>

NOTE: The use of 'collection' in the definition from <<DCAT>> is broader than
the use of the term collection in this specification. See the definition of
<<_feature_collection,'feature collection'>>.

=== distribution
represents an accessible form of a *dataset*

[.source]
<<DCAT>>

EXAMPLE: a downloadable file, an RSS feed or a web service that provides the data.

=== feature
abstraction of real world phenomena

[.source]
<<iso19101-1>>

NOTE: If you are unfamiliar with the term 'feature', the explanations in
the <<SDWBP,W3C/OGC Spatial Data on the Web Best Practice document>> may help,
in particular the section on
link:https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry[Spatial Things, Features and Geometry].

[[_feature_collection]]
=== feature collection; collection
a set of *features* from a *dataset*

NOTE: In this specification, 'collection' is used as a synonym for 'feature
collection'. This is done to make, for example, URI path expressions shorter
and easier to understand for those that are not geo-experts.
