[[overview]]
== Overview

=== This is a subtitle

This is text

CAUTION: CPoint to the POI Guide once it is available.

=== Encodings

This standard does not mandate any encoding or format for representing features or
feature collections. In addition to HTML as the standard encoding for Web content,
rules for commonly used encodings for spatial data on the web are provided
(GeoJSON, GML).

None of these encodings is mandatory and an implementation of the _Core_
requirements class may implement none of them but implement another encoding
instead.

<<rec_html,Support for HTML is recommended>> as HTML is the core language of the World Wide Web.
A server that supports HTML will support browsing the data with a web browser
and will enable search engines to crawl and index the dataset.

GeoJSON is a commonly used format that is simple to understand and well
supported by tools and software libraries. Since most Web developers are
comfortable with using a JSON-based format, this version of the Web Feature
Service standard <<rec_geojson,recommends supporting GeoJSON for encoding feature data>>,
if the feature data can be represented in GeoJSON for the intended use.

Some examples for cases that are out-of-scope of GeoJSON are:

* When solids are used as geometries (e.g. in a 3D city model),
* Geometries that include non-linear curve interpolations
that cannot be simplified (e.g., use of arcs in authoritative geometries),
* Geometries have to be represented in a coordinate reference system that
is not based on WGS 84 longitude/latitude (e.g. an authoritative national
reference system),
* Features have more than one geometric property.

The recommendations for using HTML and GeoJSON reflect the importance of HTML and
the current popularity of JSON-based data formats. As the practices
in the Web community evolve, the recommendations will likely be updated
in future versions of this standard to provide guidance on using other
encodings.

This part of the POI standard does not provide any guidance on other encodings. The
supported encodings, or more precisely the media types of the supported encodings,
can be determined from the API definition. The desired encoding is selected
using HTTP content negotiation.

For example, if the server supports
link:https://tools.ietf.org/html/rfc8142[GeoJSON Text Sequences]
an encoding that is based on JSON text sequences and GeoJSON to support streaming
by making the data incrementally parseable, the media type `application/geo+json-seq`
would be used.

In addition, HTTP supports compression and therefore the standard HTTP mechanisms
can be used to reduce the size of the messages between the server and the client.

=== Examples

This document uses a simple example throughout the document: The dataset
contains buildings and the server provides access to them through a single
feature collection ("buildings") and two encodings, GeoJSON and HTML.

The buildings have a few (optional) properties: the polygon geometry of the
building footprint, a name, the function of the building (residential,
commercial or public use), the floor count and the timestamp of the last
update of the building feature in the dataset.
