===== Abstract Feature with Lifespan

[[ats_core_featurewithlifespan]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/featurewithlifespan

target:: /req/core/featurewithlifespan

inherit:: /conf/core/abstractfeature

classification:: Target Type: Implementation Specification

test-purpose:: Validate that the Implementation Specification implements the AbstractFeaturewithLifespan Class as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Inspect the POI Implementation Specification to validate that the AbstractFeatureWithLifespan class is properly implemented.

part:: Validate that the implementation of the AbstractFeatureWithLifespan class is also a valid implementation of the AbstractFeature class using test <<ats_core_abstractfeature,/conf/core/abstractfeature>>.

part:: Validate correct implementation of the `creationDate` attribute using test <<ats_core_featurewithlifespan-creationdate,/conf/core/featurewithlifespan-creationdate>>.

part:: Validate correct implementation of the `terminationDate` attribute using test <<ats_core_featurewithlifespan-terminationdate,/conf/core/featurewithlifespan-terminationdate>>.

part:: Validate correct implementation of the `validFrom` attribute using test <<ats_core_featurewithlifespan-validfrom,/conf/core/featurewithlifespan-validfrom>>.

part:: Validate correct implementation of the `validTo` attribute using test <<ats_core_featurewithlifespan-validto,/conf/core/featurewithlifespan-validto>>.
====

====== Creation Date

[[ats_core_featurewithlifespan-creationdate]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/featurewithlifespan-creationdate
target:: /req/core/featurewithlifespan-creationdate
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `creationDate` attribute as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and type of the `creationDate` attribute.

part:: Validate that no more than one `creationDate` attribute is allowed in an AbstractFeatureWithLifespan class.

part:: Validate that the `creationDate` attribute is a valid implementation of the DateTime type from <<ISO19103,ISO 19103>>.
====

====== Termination Date

[[ats_core_featurewithlifespan-terminationdate]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/featurewithlifespan-terminationdate
target:: /req/core/featurewithlifespan-terminationdate
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `terminationDate` attribute as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and type of the `terminationDate` attribute.

part:: Validate that no more than one `terminationDate` attribute is allowed in an AbstractFeatureWithLifespan class.

part:: Validate that the `terminationDate` attribute is a valid implementation of the DateTime type from <<ISO19103,ISO 19103>>.
====

====== Valid From

[[ats_core_featurewithlifespan-validfrom]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/featurewithlifespan-validfrom
target:: /req/core/featurewithlifespan-validfrom
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `validFrom` attribute as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and type of the `validFrom` attribute.

part:: Validate that no more than one `validFrom` attribute is allowed in an AbstractFeatureWithLifespan class.

part:: Validate that the `validFrom` attribute is a valid implementation of the DateTime type from <<ISO19103,ISO 19103>>.
====

====== Valid To

[[ats_core_featurewithlifespan-validto]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/featurewithlifespan-validto
target:: /req/core/featurewithlifespan-validto
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `validTo` attribute as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and type of the `validTo` attribute.

part:: Validate that no more than one 'validTo' attribute is allowed in an AbstractFeatureWithLifespan class.

part:: Validate that the `validTo` attribute is a valid implementation of the DateTime type from <<ISO19103,ISO 19103>>.
====
