===== POI Payload

[[ats_core_poi-payload]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi_payload
target:: /req/core/poi_payload
classification:: Target Type: Implementation Specification
test-purpose:: To validate that the Implementation Specification implements the POI_Payload Class as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate that the Implementation Specification correctly implements the POI_Payload class:

part:: Validate correct implementation of the `usesSchema` aggregation using the test <<ats_core_poi_payload-usesschema,/conf/core/poi_payload-usesschema>>.

part:: Validate correct implementation of the `hasDefinition` aggregation using the test <<ats_core_poi_payload-hasdefinition,/conf/core/poi_payload-hasdefinition>>.

part:: Validate correct implementation of the `hasFeatureOfInterest` aggregation using the test <<ats_core_poi_payload-hasfeatureofinterest,/conf/core/poi_payload-hasfeatureofinterest>>.

====

====== POI_Payload Uses Schema

[[ats_core_poi_payload-usesschema]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi_payload-usesschema
target:: /req/core/poi_payload-usesschema
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `usesSchema` aggregation as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and target class of the `usesSchema` aggregation.

part:: Validate that at least one `usesSchema` aggregation is required in a POI_Payload class.

part:: Validate that the target of the `usesSchema` aggregation is a valid schema for the implementing technology.
====

====== POI_Payload Has Definition

[[ats_core_poi_payload-hasdefinition]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi_payload-hasdefinition
target:: /req/core/poi_payload-hasdefinition
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `hasDefinition` aggregation as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and target class of the `hasDefinition` aggregation.

part:: Validate that no more than one `hasDefinition` aggregation is allowed in a POI_Payload class.

part:: Validate that the target of the `hasDefinition` aggregation is a valid ontology for the implementing technology.
====

====== POI_Payload Feature Of Interest

[[ats_core_poi_payload-hasfeatureofinterest]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi_payload-hasfeatureofinterest
target:: /req/core/poi_payload-hasfeatureofinterest
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `hasFeatureOfinterest` aggregation as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and target class of the `hasFeatureOfInterest` aggregation.

part:: Validate that zero or more `hasFeatureOfInterest` aggregations are allowed in a POI_Payload class.

part:: Validate that the target of the `hasFeatureOfInterest` aggregation is a valid implementation of the Feature class from <<ISO19109,ISO 19109:2015>>.
====


