
===== Abstract POI

[[ats_core_poi-abstract-poi]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/astract-poi
target:: /req/core/abstract-poi
inherit:: /conf/core/featurewithlifespan
classification:: Target Type:Implementation Specification
test-purpose:: To validate that the Implementation Specification implements the AbstractPOI class as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

[.component,class=description]
--
Validate that the Implementation Specification correctly implements the AbstractPOI class:
--

[.component,class=part]
--
Validate that the implementation of the AbstractPOI class is also a valid implementation of the AbstractFeatureWithLIfespan class using test <<ats_core_featurewithlifespan,/conf/core/featurewithlifespan>>.
--

[.component,class=part]
--
Verify that implementations of the AbstractPOI class include a `contactInfo` attribute which is populated with a value that passes the <<ats_core_poi-contactinfo,/conf/core/poi-contactinfo>> test.
--

[.component,class=part]
--
Verify that implementations of the AbstractPOI class may include a `hasFeatureOfInterest` aggregation and that the target of that aggregation passes the <<ats_core_poi-featureofinterest,/conf/core/poi-featureOfInterest>> test.
--

[.component,class=part]
--
Verify that implementations of the AbstractPOI class may include a `hasMetadata` association and that the representation of that association passes the <<ats_core_link,/conf/core/link>> test.
--

[.component,class=part]
--
Verify that implementations of the AbstractPOI class may include a `hasPayload` aggregation and that the target of that aggregation passes the <<ats_core_poi-payload,/conf/core/poi-payload>> test.
--

[.component,class=part]
--
Verify that implementations of the AbstractPOI class may include a `keywords` attribute and that the value of that attribute passes the <<ats_core_poi-keywords,/conf/core/poi-keywords>> test.
--

[.component,class=part]
--
Verify that implementations of the AbstractPOI class may include a `rights` attribute and that the value of that attribute passes the <<ats_core_poi-rights,/conf/core/poi-rights>> test.
--

[.component,class=part]
--
Verify that implementations of the AbstractPOI class may include a `symbology` association association and that the representation of that association passes the <<ats_core_link,/conf/core/link>> test.
-- 
====

====== Abstract POI ContactInfo

[[ats_core_poi-contactinfo]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi-contactinfo
target:: /req/core/poi-contactInfo
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `contactInfo` attribute as defined in the POI Conceptual Model.

[.component,class=description]
--
Validate that the `contactInfo` attribute is a valid implementation of the CI_Responsibility class from ISO 19115-1:2014 using the OGC Team Engine and an Executable Test Suite appropriate for the implementing technology. 
--
====

====== Abstract POI Keywords

[[ats_core_poi-keywords]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi-keywords
target:: /req/core/poi-keywords
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `keywords` attribute as defined in the POI Conceptual Model.

[.component,class=description]
--
Validate that the `keywords` attribute is a valid implementation of the MD_Keyword class from ISO 19115-1:2014 using the OGC Team Engine and an Executable Test Suite appropriate for the implementing technology. 
--
====

====== Abstract POI Rights

[[ats_core_poi-rights]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi-rights
target:: /req/core/poi-rights
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `rights` attribute as defined in the POI Conceptual Model.

[.component,class=description]
--
Validate that the `contactInfo` attribute is a valid implementation of the MD_Constraints class from ISO 19115-1:2014 using the OGC Team Engine and an Executable Test Suite appropriate for the implementing technology. 
--
====

====== Link

[[ats_core_link]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/link
target:: /req/core/link
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `contactInfo` attribute as defined in the POI Conceptual Model.

[.component,class=description]
--
Validate that the `contactInfo` attribute is a valid implementation of the CI_Responsibility class from ISO 19115-1:2014 using the OGC Team Engine and an Executable Test Suite appropriate for the implementing technology. 
--
====
