==== Abstract Feature with Lifespan

[[ats_core_featurewithlifespan]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/featurewithlifespan

target:: /req/core/featurewithlifespan

inherit:: /conf/core/abstractfeature

classification:: Target Type:Implementation Specification

test-purpose:: Validate that the Implementation Specification implements the AbstractFeaturewithLifespan Class as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

[.component,class=description]
--
Validate that the AbstractFeatureWithLifespan class is properly implemented in the Implementation Specification.
--

[.component,class=part]
--
For every AbstractFeatureWithLifespan class that includes a `creationDate` attribute, validate that attribute using test <<ats_core_abstractfeature-datetime,/conf/core/abstractfeature-datetime>>.
--

[.component,class=part]
--
For every AbstractFeatureWithLifespan class that includes a `terminationDate` attribute, validate that attribute using test <<ats_core_abstractfeature-datetime,/conf/core/abstractfeature-datetime>>.
--

[.component,class=part]
--
For every AbstractFeatureWithLifespan class that includes a `validFrom` attribute, validate that attribute using test <<ats_core_abstractfeature-datetime,/conf/core/abstractfeature-datetime>>.
--

[.component,class=part]
--
For every AbstractFeatureWithLifespan class that includes a `validTo` attribute, validate that attribute using test <<ats_core_abstractfeature-datetime,/conf/core/abstractfeature-datetime>>.
--
====

===== Date-Time

[[ats_core_abstractfeature-datetime]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/abstractfeature-datetime
target:: /req/core/abstractfeature-datetime
classification:: Target Type:Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the attribute being tested as defined in ISO 19103.
test-method-type:: Manual Inspection

[.component,class=description]
--
Validate that the attribute being tested is a valid implementation of the DateTime type from ISO 19103 using the OGC Team Engine and an Executable Test Suite appropriate for the implementing technology. 
--
====


