===== Abstract Feature

[[ats_core_abstractfeature]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/abstractfeature

target:: /req/core/abstractfeature

inherit:: /conf/core/generalfeaturemodel
inherit:: /conf/core/geometry

classification:: Target Type: Implementation Specification

test-purpose:: Validate that the Implementation Specification implements the AbstractFeature Class as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Inspect the POI Implementation Specification to validate that the AbstractFeature class is properly implemented.

part:: Validate that the implementation of the AbstractFeature class is also a valid implementation of the AnyFeature class defined in the ISO 19109 General Feature Model.

part:: Validate correct implementation of the `description` attribute using test <<ats_core_abstractfeature-description,/conf/core/abstractfeature-description>>.

part:: Validate correct implementation of the `featureId` attribute using test <<ats_core_abstractfeature-featureid,/conf/core/abstractfeature-featureid>>.

part:: Validate correct implementation of the `identifier` attribute using test <<ats_core_abstractfeature-identifier,/conf/core/abstractfeature-identifier>>.

part:: Validate correct implementation of the `name` attribute using test <<ats_core_abstractfeature-name,/conf/core/abstractfeature-name>>.
--
====

====== Abstract Feature-Description

[[ats_core_abstractfeature-description]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/abstractfeature-description
target:: /req/core/abstractfeature-description
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `description` attribute as defined in the POI Conceptual Model.
test-method-type:: Manual Inspection

description:: Validate the cardinality and type of the `description` attribute.

part:: Validate that no more than one 'description' attribute is allowed in an AbstractFeature class.

part:: Validate that the `description` attribute is a valid implementation of the CharacterString class from <<ISO19103,ISO 19103>>. 
====

====== Abstract Feature-FeatureId

[[ats_core_abstractfeature-featureid]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/abstractfeature-featureid
target:: /req/core/abstractfeature-featureid
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `featureId` attribute as defined in the POI Conceptual Model.
test-method-type:: Manual Inspection

description:: Validate the cardinality and type of the `featureId` attribute.

part:: Validate that one and only one 'featureId' attribute is allowed in an AbstractFeature class.

part:: Validate that the `featureId` attribute is a valid implementation of the GenericName class from <<ISO19103,ISO 19103>>.  
====

====== Abstract Feature-Identifier

[[ats_core_abstractfeature-identifier]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/abstractfeature-identifier
target:: /req/core/abstractfeature-identifier
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `identifier` attribute as defined in the POI Conceptual Model.
test-method-type:: Manual Inspection

description:: Validate the cardinality and type of the `identifier` attribute.

part:: Validate that no more than one 'identifer' attribute is allowed in an AbstractFeature class.

part:: Validate that the `identifier` attribute is a valid implementation of the ScopedName class from <<ISO19103,ISO 19103>>.  
====

====== Abstract Feature-Name

[[ats_core_abstractfeature-name]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/abstractfeature-name
target:: /req/core/abstractfeature-name
classification:: Target Type: Implementation Specification
test-purpose:: Validate that the Implementation Specification implements the `name` attribute as defined in the POI Conceptual Model.
test-method-type:: Manual Inspection

description:: Validate the cardinality and type of the `name` attribute.

part:: Validate that zero or more 'name' attributes are allowed in an AbstractFeature class.

part:: Validate that the `name` attribute is a valid implementation of the GenericName class from <<ISO19103,ISO 19103>>.
====

