===== POI Payload

[[ats_core_poi-payload]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi-payload
target:: /req/core/poi-payload
classification:: Target Type:Implementation Specification
test-purpose:: To validate that the Implementation Specification implements the POI_Payload Class as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

[.component,class=description]
--
Do For every POI_Payload class:
--

[.component,class=part]
--
Validate that the class includes at lease one `usesSchema` aggregation and that the target of the aggregation is a valid schema for the implementing technology.
--

[.component,class=part]
--
If the class includes a `hasDefinition` aggregation, validate that the target of the aggregation is a valid ontology for the implementing technology.
--

[.component,class=part]
--
If the class includes a `hasFeatureOfInterest` aggregation, validate that the target of the aggregation is a valid Feature for the implementing technology.
--
====
