===== Geometry

[[ats_core_geometry]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/geometry

target:: /req/core/geometry

classification:: Target Type: Implementation Standard

test-purpose:: To validate that the POI Implementation Standard is conformant with the <<ISO19107,ISO 19107>> Geometry Model.

test-method-type:: Manual Inspection

description:: Inspect the POI Implementation Standard for the following:

part:: Validate that the Implementation Standard includes an Abstract Test Suite (Annex A).

part:: Validate that all geometries used in the Implementation Standard conform with the geometry model defined in <<ISO19107,ISO 19107>>.

NOTE:: If the Implementation Standard is based on a Standard known to be conformant with ISO 19107 (ex: GML), then conformance with that Standard is sufficient to show conformance with ISO 19107.

part:: Validate that the Abstract Test Suite tests each POI Feature for the presence of a `SpatialAttributeType` property of type GM_Point, GM_LineString, or GM_Polygon.

====
