
===== Abstract POI

[[ats_core_abstract-poi]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/abstract-poi
target:: /req/core/abstract-poi
inherit:: /conf/core/featurewithlifespan
classification:: Target Type: Implementation Standard
test-purpose:: To validate that the Implementation Standard implements the AbstractPOI class as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate that the Implementation Standard correctly implements the AbstractPOI class:

part:: Validate that the implementation of the AbstractPOI class is also a valid implementation of the AbstractFeatureWithLifespan class using test <<ats_core_featurewithlifespan,/conf/core/featurewithlifespan>>.

part:: Validate correct implementation of the `contactInfo` attribute using test <<ats_core_poi-contactinfo,/conf/core/poi-contactinfo>>.

part:: Validate correct implementation of the `hasFeatureOfInterest` aggregation using the test <<ats_core_poi-featureofinterest,/conf/core/poi-featureofinterest>>.

part:: Validate correct implementation of the `hasMetadata` association using the test <<ats_core_poi-metadata,/conf/core/poi-metadata>>.

part:: Validate correct implementation of the `keywords` attribute using the test <<ats_core_poi-keywords,/conf/core/poi-keywords>>.

part:: Validate correct implementation of the `rights` attribute using the test <<ats_core_poi-rights,/conf/core/poi-rights>>.

part:: Validate correct implementation of the `symbology` association using the test <<ats_core_poi-symbology,/conf/core/poi-symbology>>.

part:: Validate correct implementation of the `hasPayload` association using the test <<ats_core_poi-haspayload,/conf/core/poi-haspayload>>.

====

====== Abstract POI ContactInfo

[[ats_core_poi-contactinfo]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi-contactinfo
target:: /req/core/poi-contactInfo
classification:: Target Type: Implementation Standard
test-purpose:: Validate that the Implementation Standard implements the `contactInfo` attribute as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and type of the `contactInfo` attribute.

part:: Validate that zero or more `contactInfo` attributes are allowed in an AbstractPOI class.

part:: Validate that the `contactInfo` attribute is a valid implementation of the CI_Responsibility class from <<ISO19115,ISO 19115-1:2014>>.
====

====== Abstract POI Feature Of Interest

[[ats_core_poi-featureofinterest]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi-featureofinterest
target:: /req/core/poi-featureofinterest
classification:: Target Type: Implementation Standard
test-purpose:: Validate that the Implementation Standard implements the `hasFeatureOfinterest` aggregation as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and target class of the `hasFeatureOfInterest` aggregation.

part:: Validate that zero or more `hasFeatureOfInterest` aggregations are allowed in an AbstractPOI class.

part:: Validate that the target of the `hasFeatureOfInterest` aggregation is a valid implementation of the Feature class from <<ISO19109,ISO 19109:2015>>.
====

====== Abstract POI Metadata

[[ats_core_poi-metadata]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi-metadata
target:: /req/core/poi-metadata
classification:: Target Type: Implementation Standard
test-purpose:: Validate that the Implementation Standard implements the `hasMetadata` association as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and encoding of the `hasMetadata` association.

part:: Validate that zero or more `hasMetadata` associations are allowed in an AbstractPOI class.

part:: Validate that the `hasMetadata` association is implemented as described in the Conceptual Model using the <<ats_core_link,/conf/core/link>> test.
====

====== Abstract POI Keywords

[[ats_core_poi-keywords]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi-keywords
target:: /req/core/poi-keywords
classification:: Target Type: Implementation Standard
test-purpose:: Validate that the Implementation Standard implements the `keywords` attribute as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and type of the `keywords` attribute.

part:: Validate that zero or more `keywords` attributes are allowed in an AbstractPOI class.

part:: Validate that the `keywords` attribute is a valid implementation of the MD_Keywords class from <<ISO19115,ISO 19115-1:2014>>.
====

====== Abstract POI Rights

[[ats_core_poi-rights]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi-rights
target:: /req/core/poi-rights
classification:: Target Type: Implementation Standard
test-purpose:: Validate that the Implementation Standard implements the `rights` attribute as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and type of the `rights` attribute.

part:: Validate that zero, one, or two `rights` attributes are allowed in an AbstractPOI class.

part:: Validate that the `rights` attribute is a valid implementation of the MD_Constraints class from <<ISO19115,ISO 19115-1:2014>>.
====

====== Abstract POI Symbology

[[ats_core_poi-symbology]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi-symbology
target:: /req/core/poi-symbology
classification:: Target Type: Implementation Standard
test-purpose:: Validate that the Implementation Standard implements the `symbology` association as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and encoding of the `symbology` association.

part:: Validate that zero or one `symbology` associations are allowed in an AbstractPOI class.

part:: Validate that the `symbology` association is implemented as described in the Conceptual Model using the <<ats_core_link,/conf/core/link>> test. 
====

====== Abstract POI Payload Association

[[ats_core_poi-haspayload]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/poi-haspayload
target:: /req/core/poi-haspayload
classification:: Target Type: Implementation Standard
test-purpose:: Validate that the Implementation Standard implements the `hasPayload` aggregation as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate the cardinality and target class of the `hasPayload` aggregation.

part:: Validate that zero or more `hasPayload` aggregations are allowed in an AbstractPOI class.

part:: Validate that the target of the `hasPayload` aggregation is a valid implementation of the POI_Payload class using the <<ats_core_poi-payload,/conf/core/poi-payload>> test.
====

====== Link

[[ats_core_link]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/link
target:: /req/core/link
classification:: Target Type: Implementation Standard
test-purpose:: Validate that the Implementation Standard implements the Link class as defined in the POI Conceptual Model.

test-method-type:: Manual Inspection

description:: Validate that the association being tested uses a hyperlink approach appropriate for the implementing technology.

====
