== Terms and Definitions
This document uses the terms defined in OGC Policy Directive 49, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (OGC 08-131r3), also known as the ‘ModSpec’. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

This document uses the terms defined in OGC Policy Directive 49, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (OGC 08-131r3), also known as the ‘ModSpec’. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

The Glossary includes terms from other standards and specifications that, while not normative, are critical to accurately understand this specification.

For the purposes of this document, the following additional terms and definitions apply.

=== *location*
identifiable geographic place
(Source: ISO19112:2019)

=== *place*
identifiable part of any space
(Source: ISO19155:2012)

=== *position*
data type that describes a point or geometry potentially occupied by an object or person
(Source: ISO19133:2005)

=== *spatial reference*
system for identifying position in the real world
(Source: ISO19155:2012)

=== *stakeholder*
individual or organization having a right, share, claim, or interest in a system or in its possession of characteristics that meet their needs and expectations
(Source: ISO1588:2015)

=== *user*
individual or organization that uses the system or software to perform a specific function
(Source: ISO25000:2014)
