== Terms and Definitions
This document uses the terms defined in OGC Policy Directive 49, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (OGC 08-131r3), also known as the ‘ModSpec’. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

=== *location*
identifiable geographic place
(Source: ISO19112:2019)

=== *place*
identifiable part of any space
(Source: ISO19155:2012)

=== *position*
data type that describes a point or geometry potentially occupied by an object or person
(Source: ISO19133:2005)

=== *spatial reference*
system for identifying position in the real world
(Source: ISO19155:2012)

=== *stakeholder*
individual or organization having a right, share, claim, or interest in a system or in its possession of characteristics that meet their needs and expectations
(Source: ISO1588:2015)

The following table contains a list of stakeholder roles based on the onion model (Alexander 2005).

| Role | Scope | Description |
| ----- | ----- | ----- |
| Normal Operator | Our System | Role that involves giving routine commands and monitoring outputs from the product |
| Operational Support  | Our System | Role that involves advising normal operators of a product about how to operate it |
| Maintenance Operator | Our System | Role that involves maintaining the product |
| Interfacing Systems | Containing System | Role responsible for neighboring systems that have interfaces to and from the product |
| Sponsor or Champion | Containing System | Role responsible for initiating development of the product |
| Functional Beneficiary | Containing System | Role that benefits from the results or outputs created by the product |
| Purchaser | Containing System | Role responsible for having the product developed |
| Developer | Wider Environment | Any of the many roles involved directly in product development |
| Consultant | Wider Environment | Any of the many roles involved in supporting some aspect of product development, characteristically from outside the development organization |
| Supplier | Wider Environment | A role involved in the manufacture and provision of components for the product |
| Political Beneficiary | Wider Environment | Any role in public office or private business that can benefit in terms of power, influence, and prestige through the success of the product |
| Regulator | Wider Environment | Any role responsible for regulating the quality, safety, cost or other aspects of the product |
| Financial Beneficiary | Wider Environment | Any role that can benefit financially from the success of a product |
| Negative Stakeholder | Wider Environment | Role that could be harmed by the product physically, financially, or in any other way that might be found justifiable by the authorities |

(SOURCE: Alexander, I. F. (2005). A Taxonomy of Stakeholders: Human Roles in System Development. *International Journal of Technology and Human Interaction (IJTHI)* , 1(1), 23-59. http://doi.org/10.4018/jthi.2005010102)

=== *user*
individual or organization that uses the system or software to perform a specific function
(Source: ISO25000:2014)
