== POI Use Cases

Use cases that describe current problems or future opportunities for spatial data on the Web have been gathered as a first activity of the Working Group. They were mainly contributed by members of Working Group, but there were also contributions from other interested parties. In this chapter these use cases are listed and identified. Each use case is related to one or more Working Group <<Deliverables,deliverables>> and to one or more <<Requirements,requirements>> for future deliverables.

=== Last Mile Logistics

*Contributed By:* Timo Ruohomäki, based on innovation projects from the city of Helsinki.

<<use_case_detail_1,Click to view>> full use case description

*Related Deliverables:* ```TBD```

*Related Requirements:* ```TBD```

=== Electrical Vehicle Charging Stations

*Contributed By:* Timo Ruohomäki, based on innovation projects from the city of Helsinki.

<<use_case_detail_2,Click to view>> full use case description

*Related Deliverables:* ```TBD```

*Related Requirements:* ```TBD```

