
=== Discussion

==== Electronic Charging Ports

Well that one gets a little bit interesting when you start factoring in whether the source of that power for the electric car charging port is part of an electric grid, or whether it is a self contained solar powered unit.

In that case, the unit would be the point of interest in itself. The green aspect would be contained within that object. A power port that is connected to a building that is connected to electric grid. A Point of Interest which is a larger structure or network.

But, an electric grid can be composed of a solar charger and an EV station.

There's a lot of houses that are now completely off the off the grid. They powered powered by solar and they've got battery battery systems. They need to be connected to the grid but they they're not effectively the grid. You're using that to charge your electric bagel.

How do you describe that point of interest? Would you just describe the point point of connection or point of as the grid?

So, I don't know what the answer to that question is. It's not, or it's not obvious to me. 

It does come down to whether we're talking about the whole whole system as being an integrated system. And we're calling that whole thing a point of interest. Or whether we're calling the point of Interest as being the point by which we interact with another system. So the electricity grid as a system.

But we interact with it at certain points. At power points. Those PowerPoints themselves could potentially be points of interest.  

I was gonna say that if we approach it like that, then we, we don't necessarily need to define the whole grid in order to be able to define the point of interest.

Just before this meeting I was attending a energy industry talk. They were describing how, in the energy industry, the Digital twin is the is really. Really, really valuable, and there were like these different use cases, different energy types, and it's quite an excellent presentation by General Electric. One of the things they were describing was how having a digital twin help them to know --- operates at track efficiency and then then manipulate the physical world from the twin. 

Is there a special requirement in which a Digital Twin has a point of interest? it has to have a point on the globe in order for it to be a point of interest. But how can we capture that?

In a digital Twin that's operated by a utility, they have millions of points of interest. How do we connect with the Digital Twin?

Concepts or standards? Is my question clear?

Are we not complicating this? Should we not be looking for examples of what items we would want to have as points of interest and then potentially look at then collating them into themes and looking then where those themes come from.

So I'm wondering whether we're trying to identify things too early.

What the most use cases is, so, you know, if we have electric charge for it as 1, 1 item on the theme, we might also have windmills that generate power as another similar theme on the same G. Then we could then break that back to what was the master theme, master dataset, that theme, and then we can then drill in at that point.

But, I think we need to have a wide trawl of what people would like to see as points of interests. Of items that are points of interest, then classify them into themes. And then, for that master use case, think that's possibly a better direction. 

==== Collections of Collections

But when you're looking at it from that different perspective, you're going to be looking at individual elements of plugs and and other things like that such as filling Stations. So, there's kind of multiple levels.

So, I think there has to be kind of a built-in element of extensibility, while keeping simplicity.

I'd like to ask a chapter to respond to that. Because I remember in the original W3C work we had done, we had spent many many hours talking about how a POI can be within another POI can be within another. So, that there was this nested.

I believe that we totally have that today.

This nesting capability they refer to a group of Theo eyes as a ..., for example, certainly necessary for attracting assets, you know, in a hospital, or in a factory, or somewhere else.

Put the same model has an individual of that group. A feature can be a collection of features, which can be a collection of features that's in the model.

Therefore, a feature can be encompassed inside another feature inside another POI, right?

==== Temporal Discussion

We could integrate the theme time.

So, for example, in a case of an emergency or a disaster, a point of interest could be just open space at a certain time and under certain circumstances. There is going to be a timer.  How we could capture that or add it to the theme that we were talking about earlier?

Time-stamp and its duration, such as Valid time and valid time period are supported in the model. If you want to talk about nanoseconds and milliseconds, no, we're not quite there yet.

We're working on temporal reference systems.

The point is that work is being done on the underlying foundation that the POI is built on top of. So you'll you'll get the advantage of it without having to make the investment.

Or we can also consider the POI it may be a moving object. Which brings in a whole nother set of geometries?

Ok, there is a whole raft of philosophical questions, because by reference frame, we were moving because We're all moving, rather class.

