[[ats_core]]

=== Conformance Class Core

[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/poi/1.0/conf/core
target:: Requirements Class core
classification:: Target Type: Implementation Specification
abstract-test:: /conf/core/generalfeaturemodel
abstract-test:: /conf/core/geometry
abstract-test:: /conf/core/abstractfeature
abstract-test:: /conf/core/abstractfeature-description
abstract-test:: /conf/core/abstractfeature-featureid
abstract-test:: /conf/core/abstractfeature-identifier
abstract-test:: /conf/core/abstractfeature-name
abstract-test:: /conf/core/featurewithlifespan
abstract-test:: /conf/core/abstractfeature-creationdate
abstract-test:: /conf/core/abstractfeature-terminationdate
abstract-test:: /conf/core/abstractfeature-validfrom
abstract-test:: /conf/core/abstractfeature-validto
abstract-test:: /conf/core/abstract-poi
abstract-test:: /conf/core/poi-contactinfo
abstract-test:: /conf/core/poi-featureofinterest
abstract-test:: /conf/core/poi-metadata
abstract-test:: /conf/core/poi-keywords
abstract-test:: /conf/core/poi-rights
abstract-test:: /conf/core/poi-symbology
abstract-test:: /conf/core/poi-haspayload
abstract-test:: /conf/core/link
abstract-test:: /conf/core/poi-payload
abstract-test:: /conf/core/poi_payload/usesSchema
abstract-test:: /conf/core/poi_payload/hasDefinition
abstract-test:: /conf/core/poi_payload/featureofinterest
abstract-test:: /conf/core/poi
====

include::Core/ATS_Core_GeneralFeatureModel.adoc[]

include::Core/ATS_Core_Geometry.adoc[]

include::Core/ATS_Core_AbstractFeature.adoc[]

include::Core/ATS_Core_FeatureWithLifespan.adoc[]

include::Core/ATS_Core_AbstractPOI.adoc[]

include::Core/ATS_Core_POI_Payload.adoc[]

include::Core/ATS_Core_POI.adoc[]

